### ISSUE TITLE
Internal server error when removing a group

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1000]
When removing a group that is connected to a (probaly non-functional) SCIM server, I get an unexpected error dialog.  Log shows:

```
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /api/scim_mock/Groups?filter=externalId%20eq%20%2289cd960f-f8c7-4b39-9612-ee25cc7a7c2a%40sram.surf.nl%22 HTTP/1.1" 200 34
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /api/scim_mock/Groups?filter=externalId%20eq%20%2289cd960f-f8c7-4b39-9612-ee25cc7a7c2a%40sram.surf.nl%22 HTTP/1.1" 200 34
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: ERROR:base:user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, <Response 201 bytes [500 INTERNAL SERVER ERROR]>
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: Traceback (most recent call last):
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs/server/api/base.py", line 190, in wrapper
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     body, status = f(*args, **kwargs)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs/server/api/group.py", line 225, in delete_group
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     update_last_activity_date(collaboration.id)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     return object.__getattribute__(self, name)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     value = self._fire_loader_callables(state, key, passive)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1113, in _fire_loader_callables
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     return state._load_expired(state, passive)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     self.manager.expired_attribute_loader(self, toload, passive)
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1550, in load_scalar_attributes
Oct 09 13:36:06 app1-tf1 gunicorn[161278]:     raise orm_exc.DetachedInstanceError(
Oct 09 13:36:06 app1-tf1 gunicorn[161278]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7fbb0aaf7f40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Oct 09 13:36:06 app1-tf1 gunicorn[161248]: ERROR:user:user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0", "message": "Error: ", "url": "https://test.sram.surf.nl/static/js/main.605c616c.js", "line": 2, "col": 2471898, "error": "", "stack": "Yr/<@https://test.sram.surf.nl/static/js/main.605c616c.js:2:2471898\n", "targetUrl": "https://test.sram.surf.nl/api/groups/793", "status": 500}
Oct 09 13:36:06 app1-tf1 gunicorn[161248]: NoneType: None
Oct 09 13:36:06 app1-tf1 gunicorn[161248]: INFO:base:user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, Path /api/users/error POST {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0", "message": "Error: ", "url": "https://test.sram.surf.nl/static/js/main.605c616c.js", "line": 2, "col": 2471898, "error": "", "stack": "Yr/<@https://test.sram.surf.nl/static/js/main.605c616c.js:2:2471898\n", "targetUrl": "https://test.sram.surf.nl/api/groups/793", "status": 500}
```

To reproduce, try to remove a group here: https://test.sram.surf.nl/collaborations/3174/groups

**Comment by baszoetekouw** [comment]
Hmm, this also occurs for a CO without any services connected (and therefore seems to be not related to SCIM).  Try removing the (former service)group here: https://test.sram.surf.nl/collaborations/3177/groups 

This gives:
```
Oct 09 13:40:34 app1-tf1 gunicorn[161277]: ERROR [base] user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, <Response 201 bytes [500 INTERNAL SERVER ERROR]>
Oct 09 13:40:34 app1-tf1 gunicorn[161277]: Traceback (most recent call last):
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs/server/api/base.py", line 190, in wrapper
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     body, status = f(*args, **kwargs)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs/server/api/group.py", line 225, in delete_group
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     update_last_activity_date(collaboration.id)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     return object.__getattribute__(self, name)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     value = self._fire_loader_callables(state, key, passive)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1113, in _fire_loader_callables
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     return state._load_expired(state, passive)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     self.manager.expired_attribute_loader(self, toload, passive)
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1550, in load_scalar_attributes
Oct 09 13:40:34 app1-tf1 gunicorn[161277]:     raise orm_exc.DetachedInstanceError(
Oct 09 13:40:34 app1-tf1 gunicorn[161277]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7fbb0ca0aa90> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Oct 09 13:40:35 app1-tf1 gunicorn[161273]: ERROR:user:user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0", "message": "Error: ", "url": "https://test.sram.surf.nl/static/js/main.605c616c.js", "line": 2, "col": 2471898, "error": "", "stack": "Yr/<@https://test.sram.surf.nl/static/js/main.605c616c.js:2:2471898\n", "targetUrl": "https://test.sram.surf.nl/api/groups/794", "status": 500}
```

**Comment by baszoetekouw** [comment]
fix confirmed.
