### ISSUE TITLE
As an Org Admin, I would like to disconnect a service from a CO using the Org API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1003]
Vraag van een klant:

> Met de SRAM API kan ik wel een service connection toevoegen (put_api_collaborations_services_v1_connect_collaboration_service), maar niet verwijderen.
> 
> Kan er een nieuw endpoint bijkomen om dit mogelijk te maken?

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/596b3a08562343120818c071a3e7b3b8b7fbb7e7

**Comment by baszoetekouw** [comment]
@oharsta Ik krijg nog een 500:
```json
{
  "error": true,
  "message": "Instance <Organisation at 0x7f2b5b3f52b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)"
}
```
De call lijkt het echter wel gedaan te hebben (service wordt wel degelijk gedisconnect).

Je kan het reproduceren met:
```
╰─▶ curl -X PUT "https://test.sram.surf.nl/api/collaborations_services/v1/connect_collaboration_service" -H  "accept: application/json" -H  "Authorization: Bearer AinMPCB9Igppp_d9odnSUp_a8MK8iuC_2zoMUoR-Jt9A" -H  "Content-Type: application/json" -d '{  "short_name": "test1",  "service_entity_id": "urn:sram:bla:nogwat:sadf"}'
{"collaboration":{"organisation_short_name":"uvaaaa","short_name":"test1"},"service":{"entity_id":"urn:sram:bla:nogwat:sadf"},"status":"connected"}

╰─▶ curl -X PUT "https://test.sram.surf.nl/api/collaborations_services/v1/disconnect_collaboration_service" -H  "accept: application/json" -H  "Authorization: Bearer AinMPCB9Igppp_d9odnSUp_a8MK8iuC_2zoMUoR-Jt9A" -H  "Content-Type: application/json" -d '{  "short_name": "test1",  "service_entity_id": "urn:sram:bla:nogwat:sadf"}'
{"error":true,"message":"Instance <Organisation at 0x7f2b5f64be20> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)"}
```

**Comment by baszoetekouw** [comment]
Ik kan het nu ook niet meer reproduceren, vreemd genoeg.  De stacktrace van gisteren was deze:
```
Oct 11 15:08:54 app1-tf1 gunicorn[232988]: ERROR [base] user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, <Response 200 bytes [500 INTERNAL SERVER ERROR]>
Oct 11 15:08:54 app1-tf1 gunicorn[232988]: Traceback (most recent call last):
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs/server/api/base.py", line 190, in wrapper
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     body, status = f(*args, **kwargs)
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs/server/api/collaborations_services.py", line 149, in disconnect_collaboration_service_api
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     "organisation_short_name": organisation.short_name,
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     return object.__getattribute__(self, name)
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     value = self._fire_loader_callables(state, key, passive)
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1113, in _fire_loader_callables
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     return state._load_expired(state, passive)
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     self.manager.expired_attribute_loader(self, toload, passive)
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1550, in load_scalar_attributes
Oct 11 15:08:54 app1-tf1 gunicorn[232988]:     raise orm_exc.DetachedInstanceError(
Oct 11 15:08:54 app1-tf1 gunicorn[232988]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Organisation at 0x7f2b5b3f52b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```
