### ISSUE TITLE
PAM-weblogin pin verification endpoint returns server error when challenge wasn't visited

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1004]
PAM-weblogin pin verification endpoint returns server error when challenge wasn't used:
```
$ ssh sram@ssh-demo.sram.lab.surf.nl
(sram@ssh-demo.sram.lab.surf.nl) Please sign in to: https://sram.surf.nl/weblogin/sram_demo_pam/xxx
[QR]

Verification code: 
Server error!
```
Only after visititing the link and loggin in, I get a correct respons on a bad verification code:
```
Verification code: 
(sram@ssh-demo.sram.lab.surf.nl) Incorrect pin
```

SBS should not return a server error, but a graceful denial of the verification attempt in such cases.

**Comment by oharsta** [comment]
@mrvanes Do you have the error message / stack-trace from the server response? Or maybe the request that caused the exception?

**Comment by mrvanes** [comment]
```
Oct 12 07:12:48 sbs gunicorn[141]: DEBUG [pam_weblogin] user: Service token PAM weblogin, PamWebSSO user None new session
Oct 12 07:12:48 sbs gunicorn[141]: INFO  [base] user: Service token PAM weblogin, Path /pam-weblogin/start POST {"attribute": "username", "cache_duration": "0", "GIT_COMMIT": "x", "JSONPARSER_GIT_COMMIT": "x"}
Oct 12 07:12:53 sbs gunicorn[140]: ERROR:base:user: Service token PAM weblogin, <Response 68 bytes [500 INTERNAL SERVER ERROR]>
Oct 12 07:12:53 sbs gunicorn[140]: Traceback (most recent call last):
Oct 12 07:12:53 sbs gunicorn[140]:   File "/opt/sbs/sbs/server/api/base.py", line 190, in wrapper
Oct 12 07:12:53 sbs gunicorn[140]:     body, status = f(*args, **kwargs)
Oct 12 07:12:53 sbs gunicorn[140]:   File "/opt/sbs/sbs/server/api/pam_websso.py", line 181, in check_pin
Oct 12 07:12:53 sbs gunicorn[140]:     log_user_login(PAM_WEB_LOGIN, success, user, user.uid, service, service.entity_id, status=validation["result"])
Oct 12 07:12:53 sbs gunicorn[140]: AttributeError: 'NoneType' object has no attribute 'uid'
```
This is the _I don't know the user_id_ case.
