### ISSUE TITLE
Show error when a Service Admin inputs an invalid URL

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1005]
When a Service admin inputs an invalid URL in the "website" or "login url for users" field in the Service details (e.g., "ssh://bla@host"), pressing "Update" seems to work but in reality the value was never accepted nor saved.  Thsi only becomes clear after a hard reload of the page (which then again show the original value of the URLs).

It seems that if the URL is strange enough and does not look like a URL altogether, a correct error is shown:

![Screenshot 2023-10-12 at 09 57 20](https://github.com/SURFscz/SBS/assets/1461740/1bc73d44-c766-4f36-8357-dd0eb00d4cf8)

Indeed, in the first case the API returns a 500 (should probably be a 400-ish?):
```
Oct 12 07:58:13 app1-tf1 gunicorn[262945]: ERROR:base:user: 4bd4bfdabaa2637b6af3e1edba30962f4084ee2e@acc.sram.eduteams.org, <Response 62 bytes [500 INTERNAL SERVER ERROR]>
Oct 12 07:58:13 app1-tf1 gunicorn[262945]: Traceback (most recent call last):
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:   File "/opt/sbs/sbs/server/api/base.py", line 190, in wrapper
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:     body, status = f(*args, **kwargs)
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:   File "/opt/sbs/sbs/server/api/service.py", line 505, in update_service
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:     valid_uri_attributes(data, URI_ATTRIBUTES)
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:   File "/opt/sbs/sbs/server/db/defaults.py", line 77, in valid_uri_attributes
Oct 12 07:58:13 app1-tf1 gunicorn[262945]:     raise ValueError(f"'{uri}' is not a valid uri")
Oct 12 07:58:13 app1-tf1 gunicorn[262945]: ValueError: 'ssh://foo@bla' is not a valid uri
```
whereas in the second case, this is caught by the client.

**Comment by baszoetekouw** [comment]
works
