### ISSUE TITLE
Org Admin can view, but not edit, CO with a Unit.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1064]
Org Admin should have full access.

backtrace:
```
Nov 14 09:45:03 sbs-af2 gunicorn[386604]: ERROR:base:user: 70b5d46aa00e9f71ef4032f5620ca8624210face@acc.sram.eduteams.org, <Response 125 bytes [403 FORBIDDEN]>
Nov 14 09:45:03 sbs-af2 gunicorn[386604]: Traceback (most recent call last):
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:   File "/opt/sbs/sbs/server/api/base.py", line 191, in wrapper
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:     body, status = f(*args, **kwargs)
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 369, in collaboration_by_id
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:     confirm_collaboration_admin(collaboration_id, read_only=True)
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:   File "/opt/sbs/sbs/server/auth/security.py", line 199, in confirm_collaboration_admin
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:     confirm_read_access(override_func=override_func)
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:   File "/opt/sbs/sbs/server/auth/security.py", line 104, in confirm_read_access
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:     return confirm_scope_access(*args, override_func=override_func, scope="read")
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:   File "/opt/sbs/sbs/server/auth/security.py", line 99, in confirm_scope_access
Nov 14 09:45:03 sbs-af2 gunicorn[386604]:     raise Forbidden()
Nov 14 09:45:03 sbs-af2 gunicorn[386604]: werkzeug.exceptions.Forbidden: 403 Forbidden: Forbidden 403: https://acc.sram.surf.nl/api/collaborations/57. IP: 2001:610:450:5a::6, 10.16.0.20
```

**Comment by baszoetekouw** [comment]
tested.  Fixed in v52.2
