### ISSUE TITLE
SBS croaks on plsc/sync for COs with suspended users

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1123]
Reproduce on test after user `urn:user_deletion_warning` has actually been suspended.

User is still a member of the CO at https://github.com/SURFscz/SBS/blob/52fae118ade0e60056ff4b5e4ecbca75d3e24d17/server/api/plsc.py#L89 but user info is not captured in the CO members because of the condition here https://github.com/SURFscz/SBS/blob/52fae118ade0e60056ff4b5e4ecbca75d3e24d17/server/api/plsc.py#L56-L58

Unclear what the functional solution is.  Should user be in ldap at all, or should they have `voPersonStatus==suspended`?  Or should they be removed from CO (like for expired memberships)?

log (with additional debug info):
```
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, collaboration: {'id': 3367, 'identifier': 'da706611-0afb-4a7a-819b-b0a9c63e9b67', 'name': 'Research', 'short_name': 'research', 'global_urn': 'uva:research', 'organisation_id': 290, 'status': 'active', 'description': 'University of Amsterdam Research - Urban Crowd Control', 'logo': 'https://test.sram.surf.nl/api/images/collaborations/14cf0267-a271-4e74-ac16-c0b7a82f9fa0', 'website_url': 'https://www.google.nl', 'sbs_url': 'https://test.sram.surf.nl/collaborations/da706611-0afb-4a7a-819b-b0a9c63e9b67'}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, group: {'id': 885, 'name': 'Science', 'short_name': 'science', 'global_urn': 'uva:research:science', 'identifier': 'e46e388c-9362-4aaa-b23f-a855bf559598', 'collaboration_id': 3367, 'description': 'Science'}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, co_membership: {'collaboration_membership_id': 12190, 'group_id': 885}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, co_membership: {'collaboration_membership_id': 12362, 'group_id': 885}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, co_membership: {'collaboration_membership_id': 12191, 'group_id': 885}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, co_membership: {'collaboration_membership_id': 12192, 'group_id': 885}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: INFO  [plsc/sync] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, co_membership: {'collaboration_membership_id': 12195, 'group_id': 885}
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: ERROR [base] user: 6177eaa417edb535cf576a28d70ed7d49fc9d01e@acc.sram.eduteams.org, <Response 51 bytes [500 INTERNAL SERVER ERROR]>
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: Traceback (most recent call last):
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:   File "/opt/sbs/sbs/server/api/base.py", line 191, in wrapper
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:     body, status = f(*args, **kwargs)
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:   File "/opt/sbs/sbs/server/api/plsc.py", line 160, in syncing
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:     return internal_sync(), 200
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:   File "/opt/sbs/sbs/server/api/plsc.py", line 96, in internal_sync
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:     collaboration_membership["user_id"] = _find_user_id(collaboration_memberships,
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:   File "/opt/sbs/sbs/server/api/plsc.py", line 17, in _find_user_id
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]:     return user_ids[0]
Dec 08 13:46:39 app1-tf1 gunicorn[1885065]: IndexError: list index out of range
```

**Comment by baszoetekouw** [comment]
We should be explicit: so still show the user in the plsc output, but with an attribute `status=suspended`.  Also, please add `status=active` for all regular users.

**Comment by HarryKodden** [comment]
PLSC does not croak anymore and active users are displayed as active
