### ISSUE TITLE
Aduit log van organisation geeft 404 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1236]
Op acc en prod krijg ik een 404 op de audit log pagina van een Org.  Op test werkt het vreemd genoeg wel.
De log zegt:
```
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]: ERROR [base] user: 08882904f025223135313de0b919cb3d67bf4fbc@sram.surf.nl, <Response 66 bytes [404 NOT FOUND]>
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]: Traceback (most recent call last):
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs/server/api/base.py", line 191, in wrapper
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     body, status = f(*args, **kwargs)
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs/server/api/audit_log.py", line 104, in info
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     audit_logs = list(filter(access_collaboration_allowed, audit_logs))
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs/server/api/audit_log.py", line 100, in access_collaboration_allowed
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     collaboration = Collaboration.query.filter(Collaboration.id == audit_log.target_id).one()
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2798, in one
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     return self._iter().one()  # type: ignore
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1824, in one
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     return self._only_one_row(
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 757, in _only_one_row
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]:     raise exc.NoResultFound(
Feb 14 16:49:22 sbs-pf1 gunicorn[290373]: sqlalchemy.exc.NoResultFound: No row was found when one was required
```

**Comment by oharsta** [comment]
Also see https://github.com/SURFscz/SBS/commit/38d0b5b9f6c81b0244372c2e498e296b09957985
