### ISSUE TITLE
Logins broken with new cryptography lib

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1237]
Withe the most recent python cryptography lib (>=42), SBS logins fail:
```
Feb 15 08:36:04 sbs-pf1 gunicorn[788]: Traceback (most recent call last):
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     a list of headers, and an optional exception context to
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     if rv is None:
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     request_started.send(self, _async_wrapper=self.ensure_sync)
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     return self.make_default_options_response()
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs/server/api/user.py", line 292, in resume_session
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs/server/auth/mfa.py", line 59, in decode_jwt_token
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     kid = jwt.get_unverified_header(token)["kid"]
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs/server/auth/mfa.py", line 37, in _refresh_public_keys
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs/server/auth/mfa.py", line 37, in <dictcomp>
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/jwt/algorithms.py", line 471, in from_jwk
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     return RSAPublicNumbers(
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 423, in public_key
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     from cryptography.hazmat.backends.openssl.backend import backend
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 12, in <module>
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     from cryptography import utils, x509
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 7, in <module>
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     from cryptography.x509 import certificate_transparency, verification
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/cryptography/x509/verification.py", line 20, in <module>
Feb 15 08:36:04 sbs-pf1 gunicorn[788]:     Store = rust_x509.Store
Feb 15 08:36:04 sbs-pf1 gunicorn[788]: AttributeError: module 'x509' has no attribute 'Store'
```

**Comment by baszoetekouw** [comment]
Seems an incompatibility between the jwt and cryptography packages.

**Comment by baszoetekouw** [comment]
hmm, maybe not; might have been caused by a missed restart of sbs
