### ISSUE TITLE
Test SCIM Server hangs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1249]
On a new SCIM server registration I press 'Test' to see that the server can be reached.  SBS then only shows a white screen.

We do have a setup problem with that SCIM server in firewall settings and cluster reachability.
I expect that the TEST feature is resilient for these issues because that is precisely the reason for testing.
Suggested to execute the test in a seprated thread with a time out safety. You could also show a spinning wheel during the time out period to show that testing is in progress

An error was sent to sram-logs:
```json
{"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36", "message": "Uncaught TypeError: Cannot read properties of null (reading 'scim_url')", "url": "https://sram.surf.nl/static/js/main.10a056b6.js", "line": 2, "col": 622066, "error": "Cannot read properties of null (reading 'scim_url')", "stack": "TypeError: Cannot read properties of null (reading 'scim_url')\n    at o.renderScimResults (https://sram.surf.nl/static/js/main.10a056b6.js:2:3511587)\n    at n.value (https://sram.surf.nl/static/js/main.10a056b6.js:2:3530413)\n    at _c (https://sram.surf.nl/static/js/main.10a056b6.js:2:587323)\n    at kc (https://sram.surf.nl/static/js/main.10a056b6.js:2:587119)\n    at qs (https://sram.surf.nl/static/js/main.10a056b6.js:2:630651)\n    at vl (https://sram.surf.nl/static/js/main.10a056b6.js:2:618792)\n    at zl (https://sram.surf.nl/static/js/main.10a056b6.js:2:618720)\n    at ml (https://sram.surf.nl/static/js/main.10a056b6.js:2:618583)\n    at il (https://sram.surf.nl/static/js/main.10a056b6.js:2:615363)\n    at al (https://sram.surf.nl/static/js/main.10a056b6.js:2:613914)"}

```

**Comment by oharsta** [comment]
```
ServiceOverview.jsx:672 Uncaught TypeError: Cannot read properties of null (reading 'scim_url')
    at o.renderScimResults (ServiceOverview.jsx:672:44)
    at n.value (ServiceOverview.jsx:1290:49)
```
