### ISSUE TITLE
circular reference

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1381]
```
Bad news. An error occurred in at 2024-04-25 14:57 for user xxxx@surf.nl:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 187, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/collaboration.py", line 533, in save_collaboration
    collaboration_json = jsonify(collaboration).json
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

**Comment by baszoetekouw** [comment]
Duplicate of #1359
