### ISSUE TITLE
Service Manager should not be able to reset AUP

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1481]
Currently, he can press the button, but that causes an error:
```
Jun 19 14:23:41 sbs-af1 gunicorn[96400]: ERROR [base] user: 3c4dfafe211f2010b0ac9265407c44ed7508e620@acc.sram.eduteams.org, <Response 139 bytes [403 FORBIDDEN]>
Jun 19 14:23:41 sbs-af1 gunicorn[96400]: Traceback (most recent call last):
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:   File "/opt/sbs/sbs/server/api/base.py", line 189, in wrapper
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:     body, status = f(*args, **kwargs)
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:   File "/opt/sbs/sbs/server/api/service_aups.py", line 57, in delete_all
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:     confirm_service_admin(service_id)
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:   File "/opt/sbs/sbs/server/auth/security.py", line 246, in confirm_service_admin
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:     confirm_write_access(override_func=override_func)
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:   File "/opt/sbs/sbs/server/auth/security.py", line 126, in confirm_write_access
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:     return confirm_scope_access(*args, override_func=override_func, scope="write")
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:   File "/opt/sbs/sbs/server/auth/security.py", line 117, in confirm_scope_access
Jun 19 14:23:41 sbs-af1 gunicorn[96400]:     raise Forbidden()
```

**Comment by mrvanes** [comment]
OK
