### ISSUE TITLE
Expand demo seed to satisfy requirements for stress test ticket in description

### ISSUE THREAD

**Issue by logan-life** [SURFscz/SBS#1567]
- https://github.com/SURFscz/SBS/issues/1559
 

> Yes, and I think it makes sense to check this (and have a way to validate any optimizations). However, I don't think there is any usable demo-user available, so we need to add one in the demo seed. Not the test suite as this will break things

**Comment by HarryKodden** [comment]
Finished the work:
- Added CLI commands so, that seeds (test/demo/stress) can be initiated from command line on server (see README)
- Added tests to cover CLI commansds + seeds as well
- Seeds can also be initiated from front-end GUI (System/Seed), The stress load default parameters are then taken from config.yml on server

Running the stress load from command line provides option to generates much more seeding into the database. You can deviate from the default values:

```
$ cd server
$ FLASK_APP='__main__.py' flask stress-seed --help

Usage: flask stress-seed [OPTIONS]

  Run stress seed with specified parameters

Options:
  --users INTEGER     Number of users to create
  --orgs INTEGER      Number of organizations to create
  --collab INTEGER    Number of collaborations to create
  --services INTEGER  Number of services to create
  --groups INTEGER    Number of groups to create
  --help              Show this message and exit.
```

**Comment by mrvanes** [comment]
@HarryKodden Everything in this change is called "Stress Seed" but the System Seed tab mentions "Delete all data and insert the Anonymous Volume seed". Why the name change in the interface?

**Comment by mrvanes** [comment]
@HarryKodden Could you link the PR/commit that are linked to this issue?

**Comment by mrvanes** [comment]
Running the job in System works fine, but running it on commandline results in:
```
Starting stress seed...
config: {'num_users': 10, 'num_orgs': 10, 'num_collaborations': 1000, 'num_services': 10, 'num_groups': 10}
Error during stress seed: module 'server.db.db' has no attribute 'session'
```

**Comment by HarryKodden** [comment]
Hmm, Okke also reported this issue. I will look into what is wrong

**Comment by HarryKodden** [comment]
Proof of working:
```
...
DEBUG [root] Persisting Collaboration Memberships...
INFO  [root] meberships for collaboration: org_4:collab_998: 11
DEBUG [root] -- Creating group training with short_name group_0 for collaboration Managed non-volatile utilization with 6 members
INFO  [root] Created 1 groups for this batch
DEBUG [root] Persisting Collaboration Memberships...
INFO  [root] meberships for collaboration: org_3:collab_999: 11
DEBUG [root] -- Creating group help with short_name group_0 for collaboration Reactive local groupware with 6 members
DEBUG [root] -- Creating group perhaps with short_name group_1 for collaboration Reactive local groupware with 8 members
DEBUG [root] -- Creating group kind with short_name group_2 for collaboration Reactive local groupware with 9 members
INFO  [root] Created 3 groups for this batch
INFO  [root] Created: 1000 collaboration
DEBUG [root] Stress seed completed successfully
Stress seed completed successfully!
```

**Comment by mrvanes** [comment]
The CLI version has been fixed, but when adding 1000 CO's in the admin "System" interface, a timeout on the webinterface prevents the seed to be created:
```
DEBUG:root:Persisting Collaboration Memberships...
[2025-05-01 12:38:05 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:20)
[2025-05-01 12:38:05 +0000] [20] [ERROR] Error handling request //api/system/stress_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 54, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
    return super().__call__(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/api/base.py", line 200, in wrapper
    body, status = f(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/api/system.py", line 197, in run_stress_seed
    stress_seed(db, current_app.app_config)
  File "/opt/sbs/server/test/stress_seed.py", line 280, in stress_seed
    logger.info(f"meberships for collaboration: {collab.global_urn}: {len(collab_memberships)}")
                                                 ^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/db/logo_mixin.py", line 66, in __getattribute__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
    result = load_on_ident(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
    return load_on_pk_identity(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 705, in load_on_pk_identity
    return result.one()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1808, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 749, in _only_one_row
    row: Optional[_InterimRowType[Any]] = onerow(hard_close=True)
                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1671, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 2257, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 246, in chunks
    post_load.invoke(context, path)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1560, in invoke
    loader(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 1448, in _load_for_path
    value = lazyloader._load_for_state(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 1073, in _emit_lazyload
    stmt._compile_options += {"_current_path": effective_path}
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 789, in __add__
    o1 = self()
         ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 830, in __init__
    self.__dict__.update(kw)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-05-01 12:38:05 +0000] [20] [INFO] Worker exiting (pid: 20)
INFO:apscheduler.scheduler:Scheduler has been shut down
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
ERROR:user:user: urn:collab:person:example.com:admin, {
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "message": "Uncaught Error",
    "url": "https://sbs.dev.openconext.local/static/js/bundle.js",
    "line": 6759,
    "col": 11,
    "error": "",
    "stack": "Error\n    at https://sbs.dev.openconext.local/static/js/bundle.js:6751:21",
    "targetUrl": "https://sbs.dev.openconext.local/api/system/stress_seed",
    "status": 500
}
NoneType: None
INFO:base:user: urn:collab:person:example.com:admin, Path /api/users/error POST {"userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36", "message": "Uncaught Error", "url": "https://sbs.dev.openconext.local/static/js/bundle.js", "line": 6759, "col": 11, "error": "", "stack": "Error\n    at https://sbs.dev.openconext.local/static/js/bundle.js:6751:21", "targetUrl": "https://sbs.dev.openconext.local/api/system/stress_seed", "status": 500}
[2025-05-01 12:38:06 +0000] [187] [INFO] Booting worker with pid: 187
INFO:main:Initialize server with profile None
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

**Comment by HarryKodden** [comment]
That is 'known' behaviour. The WebInterface is not 'designed' to survive these long lasting operations. I have looked into this, but it requires much more control logic to update the front end with progress updates. To my opinion we should not go there. If you really need high numbers of data seed, then use the command line, not the web system seed.

**Comment by mrvanes** [comment]
Then I suggest to remove the stress seed button from the webinterface completely. In this form it harms the application and end users.

**Comment by mrvanes** [comment]
Currently, it looks likethe probability P for a collaboration to be connected to an organisation and a service to be connected to a collaboration is fixed? This means that for the following CLI command:
```
FLASK_APP='__main__.py' flask stress-seed --users 1 --orgs 1 --collab 1000 --services 1 --groups 1
```
Not all collaborations will be connected to the single service.

This in itself makes sense when it comes to random seeding, but it makes it hard to test https://github.com/SURFscz/SBS/issues/1789 because it would require to create ~1000+ CO's instead of 1000 to get at least 1000 CO's connected to the single service.

It would be nice to have an option to supply the probability P.

**Comment by logan-life** [comment]
Conclusion:

1. Remove the web interface part of this feature. It was a nice thought, but the CLI is a better place for the stress-loading part of this ticket.
2. Add the ability to pass in a probability `P` to affect the collaboration + service connection likelihoods. For example in #1789 we want to be able to test a service which is connected to 1000 collaborations. So probably this line can (optionally) accept a parameter to override a default. Default behavior can stay as is `(k = min(randint(0,5))`

` services=sample(services, min(randint(0, 5), len(services))),`

**Comment by mrvanes** [comment]
I would prefer to have P determine _all_ possibilities, because one day we might want to stress test 1000 users connected to a single CO as well?

**Comment by logan-life** [comment]
Sure, makes sense.

**Comment by HarryKodden** [comment]
I suggest these additional config options: (allepercentage values)
* min_co_service (default: 0)
* max_co_service (default: 5)
* min_co_user (default: 0)
* max_co_user (default: 10)

```
    # Get Service/Collaboration percentage parameters from config
    # These are the minimum and maximum percentages of services that can be
    # the default minimum percentage is 0% and the maximum percentage is 5%
    co_service_percentage_minimal = stress_config.get('min_co_service', 0)
    co_service_percentage_maximum = stress_config.get('max_co_service', 5)
    
    # Get User/Collaboration percentage parameters from config
    # These are the minimum and maximum percentages of users that can be
    # the default minimum percentage is 0% and the maximum percentage is 10%
    co_user_percentage_minimal = stress_config.get('min_co_user', 0)
    co_user_percentage_maximum = stress_config.get('max_co_user', 10)
    
    def sample_population(population, min_percentage=0, max_perscentage=100):
        a = int(min_percentage * len(population) / 100)
        b = max(a+1, int(max_perscentage * len(population) / 100))
        return sample(population, min(randint(a, b), len(population)))
```

Am i missing anything with this ?

**Comment by mrvanes** [comment]
Server config will be removed, we don't need it anymore since the system interface will be removed. I don't like the idea of mixing server config and CLI and what you suggest is much too convoluted. Let's keep it at a simple CLI parameter `-p`?

**Comment by HarryKodden** [comment]
* Server config will beremoved
* Frontend stress seed option will be removed
*  Please show me complete examples how you would to express the probabilities of Users population in a CO and the Services connected to a CO ?

**Comment by mrvanes** [comment]
To keep things simple, I would suggest using only 1 parameter to express probability. The parameter accepts a float between 0 and 1 and is the probability of a service being connected to a CO and a user being connected to a CO. Default is 0.5.

This will enable the creation of the simple test volume needed to check https://github.com/SURFscz/SBS/issues/1789 but also create complex seeds like the original design without -p param.

Specific simple 1000 CO per service test seed for 1789 e.g.
```
FLASK_APP='__main__.py' flask stress-seed --users 1 --orgs 1 --collab 1000 --services 1 --groups 1 -p 1
```

Random volume stress seed
```
FLASK_APP='__main__.py' flask stress-seed --users 50 --orgs 10 --collab 1000 --services 500 --groups 10
```
