### ISSUE TITLE
Exception in SBS

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#1606]
Seems an invitation cannot be deleted because it is still referenced.

```
Bad news. An error occurred in at 2024-09-20 12:57 for user XXXXXX@ku.edu.tr:

Traceback (most recent call last):
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`sbs`.`collaboration_memberships`, CONSTRAINT `collaboration_memberships_ibfk_3` FOREIGN KEY (`invitation_id`) REFERENCES `invitations` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 196, in wrapper
    db.session.commit()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 679, in execute
    util.preloaded.orm_persistence.delete_obj(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 193, in delete_obj
    _emit_delete_statements(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1465, in _emit_delete_statements
    c = connection.execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`sbs`.`collaboration_memberships`, CONSTRAINT `collaboration_memberships_ibfk_3` FOREIGN KEY (`invitation_id`) REFERENCES `invitations` (`id`))')
[SQL: DELETE FROM invitations WHERE invitations.id = %s]
[parameters: (16226,)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

Sent by [SURF Research Access Management](https://edu.nl/vw3jx) (SRAM).

A service by [SURF](https://surf.nl/en).
```

**Comment by oharsta** [comment]
If an invitation created by the external API is accepted, then it is no longer possible to delete the invitation caused by the foreign key constraint in collaboration_memberships. Solved by changing the FK with `ON DELETE SET NULL`.

**Comment by mrvanes** [comment]
I don't understand how to test. As far as I know, invitations get deleted when accepted, so where could this invitation then be deleted and about what invitations are we talking? How to reproduce?

**Comment by oharsta** [comment]
Invitations created with the external API (e.g. not in the GUI) are not deleted when accepted. There is a FK in the collaboration_membership referencing this invitation. Therefore the invitation could not deleted with the API. This is solved by changing the FK in collaboration_membership to `ON DELETE SET NULL`

**Comment by mrvanes** [comment]
In that case, I _think_ I was looking at fixed behaviour because I couldn't find the invitation after accepting an API invitation ;)
Case closed.
