### ISSUE TITLE
Bad Request: encrypt_scim_bearer_token requires scim_bearer_token and scim_url

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SBS#1623]
```
INFO  [resume-session/user] user: ext_api, Updating user user1 with new claims / updated at
DEBUG [resume-session/user] user: ext_api, user user1: idp_mfa=True (ACR = 'https://refeds.org/profile/mfa')
DEBUG [redirect] user: ext_api, Redirecting user user1 to https://sbs.scz-vm.net/invitations/accept/AVehHbFOLcOKGeDbHrB0-A4C4iR1jYHE_1DkkzevZjhE
ERROR [scim] Error in applying SCIM change
Traceback (most recent call last):
  File "/opt/sbs/server/scim/scim.py", line 31, in wrapper
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/scim/scim.py", line 233, in apply_collaboration_change
    _do_apply_group_collaboration_change(group, services, deletion)
  File "/opt/sbs/server/scim/scim.py", line 177, in _do_apply_group_collaboration_change
    scim_object = _lookup_scim_object(service, SCIM_GROUPS, group.identifier)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/scim/scim.py", line 137, in _lookup_scim_object
    response = requests.get(url, headers=scim_headers(service), timeout=10)
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/scim/scim.py", line 67, in scim_headers
    plain_bearer_token = decrypt_scim_bearer_token(service)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/auth/tokens.py", line 61, in decrypt_scim_bearer_token
    encryption_key = _get_encryption_key(service)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sbs/server/auth/tokens.py", line 20, in _get_encryption_key
    raise BadRequest("encrypt_scim_bearer_token requires scim_bearer_token and scim_url")
werkzeug.exceptions.BadRequest: 400 Bad Request: encrypt_scim_bearer_token requires scim_bearer_token and scim_url
INFO  [base] user: user1, Path /api/invitations/accept PUT {"hash": "AVehHbFOLcOKGeDbHrB0-A4C4iR1jYHE_1DkkzevZjhE"}
```

**Comment by oharsta** [comment]
@FlorisFokkinga This is not a bug, but the result of a misconfiguration. In order to perform a SCIM lookup at a remote SCIM server, we need to decrypt the token. The Service is configured to have SCIM changes applied, but lacks the token to do this. The behaviour is as designed. I have added logging so it is more clear which service is misconfigured.

**Comment by mrvanes** [comment]
Fixed:
`ERROR [scim] Error (absorbed) during SCIM exchange (400 Bad Request: encrypt_scim_bearer_token for service SCIM requires scim_bearer_token (None) and scim_url (https://sbs.scz-vm.net/api/scim_mock))`
