### ISSUE TITLE
SBS error

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#220]
Een gebruiker krigjt de volgende error:

```
SBS: 2022-06-27 07:43:01,102 base ERROR user: 8441a4c50e66d7e9313e2c062877c56b2587ae59@sram.surf.nl, <Response 79 bytes [500 INTERNAL SERVER ERROR]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 130, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/collaboration.py", line 105, in name_exists
    organisation_id = int(query_param("organisation_id"))
ValueError: invalid literal for int() with base 10: 'undefined'
```

access log zegt:
```
jun 27 07:42:39 sbs-pf2 apache2[50086]: [27/Jun/2022:07:42:39 +0000] sbs-pf2.internal.sram.surf.nl 10.0.0.20 80.112.16.38 - HTTP/1.1 GET 200 3395 "/api/collaboration_requests/91"
 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15" "https://sram.surf.nl/collaboration-requests/91"
jun 27 07:42:39 sbs-pf2 apache2[50086]: [27/Jun/2022:07:42:39 +0000] sbs-pf2.internal.sram.surf.nl 10.0.0.20 80.112.16.38 - HTTP/1.1 GET 200 65030 "/api/images/collaboration_requ
ests/6a90c23c-d8bf-4370-9cb5-1412d0b9d64f" "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15" "https://sra
m.surf.nl/collaboration-requests/91"
jun 27 07:43:01 sbs-pf2 apache2[50086]: [27/Jun/2022:07:43:01 +0000] sbs-pf2.internal.sram.surf.nl 10.0.0.20 80.112.16.38 - HTTP/1.1 GET 500 1158 "/api/collaborations/name_exists
" "?name=masterthesisproj&organisation_id=undefined&existing_collaboration=null" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version
/15.5 Safari/605.1.15" "https://sram.surf.nl/collaboration-requests/91"
```

@oharsta Kun jij hieraan zien hoe dit kan gebeuren?

**Comment by oharsta** [comment]
@baszoetekouw Bug in het accepteren van een collaboration request. De collaboration admin kan de name en short_name veranderen en dan ging de validatie of deze al bestaat mis.

**Comment by baszoetekouw** [comment]
tested.
