### ISSUE TITLE
cannot impersonate urn:john on test

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#256]
I tried to impersonate urn:john on test from a service page https://test.sram.surf.nl/services/312/admins

This resulted in an error in the UI and  stack trace in the log:
```
SBS: 2022-08-05 13:59:23,383 base ERROR user: 9bf251bf6cfa9eb8c75f15a90075fa7074eb3d48@acc.sram.eduteams.org, <Response 55 bytes [500 INTERNAL SERVER ERROR]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 130, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/user.py", line 554, in other
    return _user_json_response(user, True)
  File "/opt/sbs/sbs/server/api/user.py", line 104, in _user_json_response
    _add_service_aups(json_user, user)
  File "/opt/sbs/sbs/server/api/user.py", line 67, in _add_service_aups
    user["services_without_aup"] = jsonify(unique_missing_services).json
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

**Comment by FlorisFokkinga** [comment]
I can impersonate John the service admin. Has this been fixed? I don't see a commit message in this issues.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/80269262/187387834-76e7ea83-bd99-48cb-9d77-e875edd7e48b.png">

**Comment by oharsta** [comment]
Has been fixed.

**Comment by HarryKodden** [comment]
Checked, works !
