### ISSUE TITLE
Pam-weblogin api geeft 500 als gebruiker niet gevonden is

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#274]
SBS geeft:
```
SBS: 2022-08-04 13:23:54,929 base ERROR user: Service token Pam-weblogin Test, <Response 65 bytes [500 INTERNAL SERVER ERROR]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 130, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 78, in start
    raise NotFound(f"User {filters} not found")
werkzeug.exceptions.NotFound: 404 Not Found: User {'uid': 'unspecified'} not found
```
waardoor de pam module ene 500 ontvangt ipv een 404.

Zie https://github.com/SURFscz/pam-weblogin/issues/20

**Comment by oharsta** [comment]
@baszoetekouw Heb je voor mij de hele log? Want in de integratie testen wordt er netjes een 404 teruggeven. Komt die 500 wel van SBS of komt die van de pamtester? Zie ook https://github.com/SURFscz/SBS/blob/main/server/test/api/test_pam_websso.py#L60

**Comment by oharsta** [comment]
En de curl:
```
curl -vik -d '{"user_id": "nope","attribute": "email","cache_duration": 300}' -H "Authorization: bearer ATSAtpSkHlP6_rrETAugQDJFl-5Yly1FfTCBpduYHJoY" -H "Content-Type: application/json" -X POST "http://localhost:8080/pam-weblogin/start"
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /pam-weblogin/start HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> Authorization: bearer ATSAtpSkHlP6_rrETAugQDJFl-5Yly1FfTCBpduYHJoY
> Content-Type: application/json
> Content-Length: 62
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 404 NOT FOUND
HTTP/1.0 404 NOT FOUND
< Server: Werkzeug/2.2.2 Python/3.7.3
Server: Werkzeug/2.2.2 Python/3.7.3
< Date: Fri, 19 Aug 2022 10:48:11 GMT
Date: Fri, 19 Aug 2022 10:48:11 GMT
< Content-Type: application/json
Content-Type: application/json
< Content-Length: 60
Content-Length: 60
< x-session-alive: true
x-session-alive: true
< server: 
server: 
< Vary: Cookie
Vary: Cookie
< Connection: close
Connection: close

< 
{"error":true,"message":"User {'email': 'nope'} not found"}
```

**Comment by oharsta** [comment]
De logging is wel een bug, want de error wordt gelogd en pas daarna wordt de juiste status op de exception gezet. Zie https://github.com/SURFscz/SBS/blob/main/server/api/base.py#L147

**Comment by oharsta** [comment]
Logging fixed in https://github.com/SURFscz/SBS/commit/fd84614eb9893854639d96b37d39725a895ff538. And now the server logs this:
```
ERROR:base:user: Service token Storage, <Response 60 bytes [404 NOT FOUND]>
Traceback (most recent call last):
  File "/Users/okkeharsta/projects/SBS/server/api/base.py", line 137, in wrapper
    body, status = f(*args, **kwargs)
  File "/Users/okkeharsta/projects/SBS/server/api/pam_websso.py", line 82, in start
    raise NotFound(f"User {filters} not found")
werkzeug.exceptions.NotFound: 404 Not Found: User {'email': 'nope'} not found
INFO:werkzeug:127.0.0.1 - - [19/Aug/2022 12:53:21] "POST /pam-weblogin/start HTTP/1.1" 404 -
```

**Comment by baszoetekouw** [comment]
You're right; SBS actually returns a 404 according to the haproxy logs.
