### ISSUE TITLE
CO admins kunnen geen diensten meer koppelen/ontkoppelen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#284]
Sinds kort lijken CO-admins geen toestemming meer te hebben om services te koppelen en ontkoppelen.  

Kale CO-admins (die geen platform-admin zijn) zien bij de beschikbare diensten voor een CO alleen een lege lijst.  Ze zien wel diensten die al gekoppeld zijn (met een Disconnect-knop), maar als ze die proberen te disconnecten krijgen ze een "This is embarrassing..."-error).  De bijbehorende dump is:
```
SBS: 2022-08-29 14:36:36,178 base INFO user: 9bf251bf6cfa9eb8c75f15a90075fa7074eb3d48@acc.sram.eduteams.org, Path /api/collaborations_services PUT {"collaboration_id": 2983, "service_id": 311}
SBS: 2022-08-29 14:36:46,420 base INFO user: 47c0c59a7b098d55bea53555080ff88d9bcba524@acc.sram.eduteams.org, Path /api/service_aups/bulk POST {"service_identifiers": [311]}
SBS: 2022-08-29 14:36:51,169 base ERROR user: 47c0c59a7b098d55bea53555080ff88d9bcba524@acc.sram.eduteams.org, <Response 150 bytes [403 FORBIDDEN]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 137, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/collaborations_services.py", line 126, in delete_collaborations_services
    confirm_write_access()
  File "/opt/sbs/sbs/server/auth/security.py", line 98, in confirm_write_access
    return confirm_scope_access(*args, override_func=override_func, scope="write")
  File "/opt/sbs/sbs/server/auth/security.py", line 89, in confirm_scope_access
    raise Forbidden()
werkzeug.exceptions.Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
SBS: 2022-08-29 14:36:51,447 user ERROR user: 47c0c59a7b098d55bea53555080ff88d9bcba524@acc.sram.eduteams.org, {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0", "message": "Error: Forbidden", "url": "https://test.sram.surf.nl/static/js/main.7d1aed29.js", "line": 2, "col": 1525368, "error": "Forbidden", "stack": "dt/<@https://test.sram.surf.nl/static/js/main.7d1aed29.js:2:1525368\n", "targetUrl": "https://test.sram.surf.nl/api/collaborations_services/2983/311", "status": 403}
NoneType: None
SBS: 2022-08-29 14:36:51,447 base INFO user: 47c0c59a7b098d55bea53555080ff88d9bcba524@acc.sram.eduteams.org, Path /api/users/error POST {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0", "message": "Error: Forbidden", "url": "https://test.sram.surf.nl/static/js/main.7d1aed29.js", "line": 2, "col": 1525368, "error": "Forbidden", "stack": "dt/<@https://test.sram.surf.nl/static/js/main.7d1aed29.js:2:1525368\n", "targetUrl": "https://test.sram.surf.nl/api/collaborations_services/2983/311", "status": 403}
```

Reproduceerbaar op zowel prod als test.

**Comment by baszoetekouw** [comment]
Jup, heb het even gechecked: beide COs die ik had geprobeerd zaten idd in een SURF Org.  Omschakelen naar een normale Org lost het probleem op.

**Comment by baszoetekouw** [comment]
Werkt nu correct.
