### ISSUE TITLE
Access denied error op pam-weblogin te verbose in log

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#297]
Een access denied error op het pam-weblogin endpoint is nu tamelijk verbose:
```
SBS: 2022-08-31 08:21:14,816 base ERROR user: ext_api, <Response 248 bytes [500 INTERNAL SERVER ERROR]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 130, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 63, in start
    service = validate_service_token("pam_web_sso_enabled")
  File "/opt/sbs/sbs/server/auth/tokens.py", line 21, in validate_service_token
    raise Unauthorized()
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
```

In plaats hiervan zie ik graag 1 regel met een foutmelding, welk endpoint er aangeroepen werd, en vanaf welk ip.  Is het nmogelojk om dat generiek af te vangen in flask?  Want volgens mij hebben we dit vaker gehad.

**Comment by mrvanes** [comment]
Ik zie met b07da8c7602c393a918445e79014230bbf568117 nog steeds deze log in sbs[_debug].log:
```
SBS: 2022-09-07 12:39:50,744 base ERROR user: ext_api, <Response 322 bytes [401 UNAUTHORIZED]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 143, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 67, in start
    service = validate_service_token("pam_web_sso_enabled")
  File "/opt/sbs/sbs/server/auth/tokens.py", line 21, in validate_service_token
    raise Unauthorized()
werkzeug.exceptions.Unauthorized: 401 Unauthorized: Unauthorized: https://sbs.scz-vm.net/pam-weblogin/start. IP: 172.20.1.24. The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
```

**Comment by mrvanes** [comment]
Ik zie met b07da8c7602c393a918445e79014230bbf568117 nog steeds deze log in sbs[_debug].log:
```
SBS: 2022-09-07 12:39:50,744 base ERROR user: ext_api, <Response 322 bytes [401 UNAUTHORIZED]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 143, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 67, in start
    service = validate_service_token("pam_web_sso_enabled")
  File "/opt/sbs/sbs/server/auth/tokens.py", line 21, in validate_service_token
    raise Unauthorized()
werkzeug.exceptions.Unauthorized: 401 Unauthorized: Unauthorized: https://sbs.scz-vm.net/pam-weblogin/start. IP: 172.20.1.24. The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
```

**Comment by mrvanes** [comment]
Running b99051273bdd61fcc537a01b8c38f3ca3adbcc99 and still seeing
```
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 143, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 67, in start
    service = validate_service_token("pam_web_sso_enabled")
  File "/opt/sbs/sbs/server/auth/tokens.py", line 21, in validate_service_token
    raise Unauthorized()
werkzeug.exceptions.Unauthorized: 401 Unauthorized: Unauthorized 401: https://sbs.scz-vm.net/pam-weblogin/start. IP: 172.20.1.24

```

**Comment by oharsta** [comment]
@baszoetekouw @mrvanes  I misread, I thought you wanted a less generic exception description. Personally I'm not in favour of of discarding the stack-trace. If we generically discard stack-traces then we miss the information where the exception occurred. `Unauthorized` and `Forbidden` are raises on various places in the codebase and some occurrences might be interesting. If you do want to discard the stack-trace it is of course a very small change.

**Comment by baszoetekouw** [comment]
@oharsta makes sense to not discard the stack trace  However, would it be possible to enter a generic "permission denied for X while trying Y" in the info log, and putting the stack trace in the debug log?  Currently the stack trace is in both sbs.log and sbs_debug.log.
