### ISSUE TITLE
Error while accepting connection request for service

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#407]
Situatie:
service met daaraan 1 CO gekoppeld.  Service heeft 2 service groups: een normale en 1 met autoprovisioning.
Nieuwe CO doet connection request. Na accept van de service admin volgt deze error:

```
Nov 16 10:44:01 sbs-af1 python[61787]: ERROR [base] user: 02d69f7cad3fcfb44b4e7a4a5ebfbcb1b183ef4d@acc.sram.eduteams.org, <Response 166 bytes [403 FORBIDDEN]>
Nov 16 10:44:01 sbs-af1 python[61787]: Traceback (most recent call last):
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/base.py", line 149, in wrapper
Nov 16 10:44:01 sbs-af1 python[61787]:     body, status = f(*args, **kwargs)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/service_connection_request.py", line 156, in approve_service_connection_request
Nov 16 10:44:01 sbs-af1 python[61787]:     return _do_service_connection_request(hash_value, True)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/service_connection_request.py", line 41, in _do_service_connection_request
Nov 16 10:44:01 sbs-af1 python[61787]:     connect_service_collaboration(service.id, collaboration.id, force=True)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/collaborations_services.py", line 35, in connect_service_collaboration
Nov 16 10:44:01 sbs-af1 python[61787]:     create_service_groups(service, collaboration)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/service_group.py", line 26, in create_service_groups
Nov 16 10:44:01 sbs-af1 python[61787]:     create_group(collaboration.id, data, do_cleanse_short_name=False)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/group.py", line 115, in create_group
Nov 16 10:44:01 sbs-af1 python[61787]:     auto_provision_all_members_and_invites(res[0])
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/group.py", line 40, in auto_provision_all_members_and_invites
Nov 16 10:44:01 sbs-af1 python[61787]:     do_add_group_members({
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/api/group_members.py", line 18, in do_add_group_members
Nov 16 10:44:01 sbs-af1 python[61787]:     confirm_collaboration_admin(collaboration_id)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/auth/security.py", line 169, in confirm_collaboration_admin
Nov 16 10:44:01 sbs-af1 python[61787]:     confirm_write_access(override_func=override_func)
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/auth/security.py", line 97, in confirm_write_access
Nov 16 10:44:01 sbs-af1 python[61787]:     return confirm_scope_access(*args, override_func=override_func, scope="write")
Nov 16 10:44:01 sbs-af1 python[61787]:   File "/opt/sbs/sbs/server/auth/security.py", line 88, in confirm_scope_access
Nov 16 10:44:01 sbs-af1 python[61787]:     raise Forbidden()
Nov 16 10:44:01 sbs-af1 python[61787]: werkzeug.exceptions.Forbidden: 403 Forbidden: Forbidden 403: http://acc.sram.surf.nl/api/service_connection_requests/approve/AEewHJzp_0UcQDgpfgFBa3z6PnTYZqSJZjEsVPHwfDzs. IP: 127.0.0.1
```

**Comment by baszoetekouw** [comment]
Resultaat is dat de CO de dienst gekoppeld heeft, maar dat de Service request blijft open staan.  De service groepen zijn aangemaakt, maar gebruikers zijn niet geprovisioned.

![Screenshot 2022-11-16 at 11 50 43](https://user-images.githubusercontent.com/1461740/202161223-dd14e9c5-40ed-4480-a10e-4e719796fc97.png)

**Comment by baszoetekouw** [comment]
Niet geheel verrassend gaat het wel goed als je de connection request als platformadmin accepteert.

**Comment by baszoetekouw** [comment]
tested
