### ISSUE TITLE
Bug in create group with invites and auto-provisioning

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#438]
Create Group in CO with auto_provisioning and the collaboration has open invites
```
sbs-1-server-1  | [pid: 1|app: 0|req: 167/167] 172.27.0.5 () {54 vars in 1620 bytes} [Thu Dec  8 15:38:46 2022] GET /api/groups/name_exists?name=yyy&collaboration_id=1&existing_group=null => generated 6 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 117 bytes (1 switches on core 0)
sbs-1-server-1  | [pid: 1|app: 0|req: 168/168] 172.27.0.5 () {54 vars in 1644 bytes} [Thu Dec  8 15:38:50 2022] GET /api/groups/short_name_exists?short_name=yyy&collaboration_id=1&existing_group=null => generated 6 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 117 bytes (1 switches on core 0)
sbs-1-client-1  | 172.27.0.1 - - [08/Dec/2022:15:38:50 +0000] "GET /api/groups/short_name_exists?short_name=yyy&collaboration_id=1&existing_group=null HTTP/1.1" 200 6 "http://localhost:8080/collaborations/1/groups" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0" "-"
sbs-1-server-1  | ERROR [base] user: 72e8fabfeca6a933d2eb97dc96053f10dc49fd8d@acc.sram.eduteams.org, <Response 219 bytes [500 INTERNAL SERVER ERROR]>
sbs-1-server-1  | Traceback (most recent call last):
sbs-1-server-1  |   File "./server/api/base.py", line 156, in wrapper
sbs-1-server-1  |     body, status = f(*args, **kwargs)
sbs-1-server-1  |   File "/usr/local/lib/python3.7/site-packages/flask_jsonschema_validator/jsonschemavalidator.py", line 55, in decorated
sbs-1-server-1  |     return func( *args, **kwargs )
sbs-1-server-1  |   File "./server/api/group.py", line 101, in save_group
sbs-1-server-1  |     res = create_group(collaboration_id, data)
sbs-1-server-1  |   File "./server/api/group.py", line 117, in create_group
sbs-1-server-1  |     auto_provision_all_members_and_invites(res[0])
sbs-1-server-1  |   File "./server/api/group.py", line 48, in auto_provision_all_members_and_invites
sbs-1-server-1  |     ag_invitation_identifiers = [i.id for i in group.invitations]
sbs-1-client-1  | 172.27.0.1 - - [08/Dec/2022:15:38:55 +0000] "POST /api/groups HTTP/1.1" 500 219 "http://localhost:8080/collaborations/1/groups" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0" "-"
sbs-1-server-1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
sbs-1-server-1  |     return self.impl.get(state, dict_)
sbs-1-server-1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
sbs-1-server-1  |     value = self._fire_loader_callables(state, key, passive)
sbs-1-server-1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
sbs-1-server-1  |     return self.callable_(state, passive)
sbs-1-server-1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 865, in _load_for_state
sbs-1-server-1  |     % (orm_util.state_str(state), self.key)
sbs-1-server-1  | sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Group at 0xffffab74a890> is not bound to a Session; lazy load operation of attribute 'invitations' cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
sbs-1-server-1  | [pid: 1|app: 0|req: 169/169] 172.27.0.5 () {58 vars in 1559 bytes} [Thu Dec  8 15:38:55 2022] POST /api/groups => generated 219 bytes in 346 msecs (HTTP/1.1 500) 5 headers in 138 bytes (1 switches on core 0)
sbs-1-server-1  | [pid: 1|app: 0|req: 170/170] 172.27.0.5 () {54 vars in 1579 bytes} [Thu Dec  8 15:38:56 2022] GET /api/organisations/find_by_schac_home_organisation => generated 3 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 117 bytes (1 switches on core 0)
sbs-1-client-1  | 172.27.0.1 - - [08/Dec/2022:15:38:56 +0000] "GET /api/organisations/find_by_schac_home_organisation HTTP/1.1" 200 3 "http://localhost:8080/collaborations/1/groups" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0" "-"
sbs-1-server-1  | ERROR [user] user: 72e8fabfeca6a933d2eb97dc96053f10dc49fd8d@acc.sram.eduteams.org, {"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0", "message": "Error: INTERNAL SERVER ERROR", "url": "http://localhost:8080/static/js/main.970621ca.js", "line": 2, "col": 1549025, "error": "INTERNAL SERVER ERROR", "stack": "Wn/<@http://localhost:8080/static/js/main.970621ca.js:2:1549025\n", "targetUrl": "http://localhost:8080/api/groups", "status": 500}
sbs-1-server-1  | NoneType: None
```

**Comment by oharsta** [comment]
Solved in feature/scim-sweep

**Comment by mrvanes** [comment]
Getest door Martin met een tail op de sram-sbs log.
