### ISSUE TITLE
Don't send error log message by email when receiving invalid json

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#477]
The following exception trigger log message sent to sram-logs:
```
Jan 19 16:17:10 sbs-pf1 python[4662]: ERROR [base] user: Service token XXXX SSH gateway, <Response 175 bytes [400 BAD REQUEST]>
Jan 19 16:17:10 sbs-pf1 python[4662]: Traceback (most recent call last):
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 578, in get_json
Jan 19 16:17:10 sbs-pf1 python[4662]:     rv = self.json_module.loads(data)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/provider.py", line 255, in loads
Jan 19 16:17:10 sbs-pf1 python[4662]:     return json.loads(s, **kwargs)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
Jan 19 16:17:10 sbs-pf1 python[4662]:     return _default_decoder.decode(s)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
Jan 19 16:17:10 sbs-pf1 python[4662]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
Jan 19 16:17:10 sbs-pf1 python[4662]:     obj, end = self.scan_once(s, idx)
Jan 19 16:17:10 sbs-pf1 python[4662]: json.decoder.JSONDecodeError: Invalid control character at: line 1 column 61 (char 60)
Jan 19 16:17:10 sbs-pf1 python[4662]: During handling of the above exception, another exception occurred:
Jan 19 16:17:10 sbs-pf1 python[4662]: Traceback (most recent call last):
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
Jan 19 16:17:10 sbs-pf1 python[4662]:     return super().on_json_loading_failed(e)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 609, in on_json_loading_failed
Jan 19 16:17:10 sbs-pf1 python[4662]:     raise BadRequest(f"Failed to decode JSON object: {e}")
Jan 19 16:17:10 sbs-pf1 python[4662]: werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Invalid control character at: line 1 column 61 (char 60)
Jan 19 16:17:10 sbs-pf1 python[4662]: The above exception was the direct cause of the following exception:
Jan 19 16:17:10 sbs-pf1 python[4662]: Traceback (most recent call last):
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs/server/api/base.py", line 156, in wrapper
Jan 19 16:17:10 sbs-pf1 python[4662]:     body, status = f(*args, **kwargs)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs/server/api/pam_websso.py", line 138, in check_pin
Jan 19 16:17:10 sbs-pf1 python[4662]:     data = current_request.get_json()
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 587, in get_json
Jan 19 16:17:10 sbs-pf1 python[4662]:     rv = self.on_json_loading_failed(e)
Jan 19 16:17:10 sbs-pf1 python[4662]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/wrappers.py", line 133, in on_json_loading_failed
Jan 19 16:17:10 sbs-pf1 python[4662]:     raise BadRequest() from e
Jan 19 16:17:10 sbs-pf1 python[4662]: werkzeug.exceptions.BadRequest: 400 Bad Request: BadRequest: http://sram.surf.nl/pam-weblogin/check-pin. IP: 127.0.0.1. The browser (or proxy) sent a request that this server could not understand.
Jan 19 16:17:10 sbs-pf1 python[4662]: DEBUG [user] user: Service token XXXX SSH gateway, Sending mail message to sram-logs@surf.nl with Message-id <5666290b.4e56.4c60.93ce.509a28facaca@sbs.pf1.internal.sram.surf.nl>
```
Please disable the email message (while keeping the eexception (or a friendlier error) in the log

**Comment by baszoetekouw** [comment]
Foute jsons geven nog steeds een error mail.

Na het voeren van invalid json (haakje weggehaald in het standaard voorbeeld in de apidocs voor /api/collaborations/v1) krijg ik nog:

![Screenshot 2023-03-10 at 15 45 49](https://user-images.githubusercontent.com/1461740/224345782-ae412366-07c3-46e1-a4fe-313fe164f2a7.png)

**Comment by mrvanes** [comment]
Ik krijg geen mail meer in VM deploy
