### ISSUE TITLE
Please replace exception by useful error message

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#478]
Please replace this exception
```
Jan 19 02:30:09 sbs-pf2 python[2515]: ERROR [base] user: ext_api, <Response 114 bytes [401 UNAUTHORIZED]>
Jan 19 02:30:09 sbs-pf2 python[2515]: Traceback (most recent call last):
Jan 19 02:30:09 sbs-pf2 python[2515]:   File "/opt/sbs/sbs/server/api/base.py", line 152, in wrapper
Jan 19 02:30:09 sbs-pf2 python[2515]:     auth_filter(current_app.app_config)
Jan 19 02:30:09 sbs-pf2 python[2515]:   File "/opt/sbs/sbs/server/api/base.py", line 89, in auth_filter
Jan 19 02:30:09 sbs-pf2 python[2515]:     raise Unauthorized(description="Invalid API key")
Jan 19 02:30:09 sbs-pf2 python[2515]: werkzeug.exceptions.Unauthorized: 401 Unauthorized: Unauthorized: http://sram.surf.nl/api/organisations/v1. IP: 127.0.0.1. Invalid API key
```
 (which occurs frequently)  by a proper error message, which includes the source ip and the endpoint/call it is trying to make.

**Comment by oharsta** [comment]
The stack-trace can only be suppressed if we don't raise the error, but we must to stop the control flow. The last line is:
```
Unauthorized: http://sram.surf.nl/api/organisations/v1. IP: 127.0.0.1. Invalid API key
```
The IP is now being replaced with the X-Forwarded-for header, and the endpoint / call is mentioned. E.g. http://sram.surf.nl/api/organisations/v1
