### ISSUE TITLE
Replace exception by "invitation not found" message

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#479]
Please replace this excpetion by a regular error message in the logs:
```
Jan 19 08:12:55 sbs-pf2 python[4734]: ERROR [base] user: ext_api, <Response 66 bytes [404 NOT FOUND]>
Jan 19 08:12:55 sbs-pf2 python[4734]: Traceback (most recent call last):
Jan 19 08:12:55 sbs-pf2 python[4734]:   File "/opt/sbs/sbs/server/api/base.py", line 156, in wrapper
Jan 19 08:12:55 sbs-pf2 python[4734]:     body, status = f(*args, **kwargs)
Jan 19 08:12:55 sbs-pf2 python[4734]:   File "/opt/sbs/sbs/server/api/invitation.py", line 63, in invitations_by_hash
Jan 19 08:12:55 sbs-pf2 python[4734]:     invitation = invitation_query \
Jan 19 08:12:55 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2869, in one
Jan 19 08:12:55 sbs-pf2 python[4734]:     return self._iter().one()
Jan 19 08:12:55 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1476, in one
Jan 19 08:12:55 sbs-pf2 python[4734]:     return self._only_one_row(
Jan 19 08:12:55 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
Jan 19 08:12:55 sbs-pf2 python[4734]:     raise exc.NoResultFound(
Jan 19 08:12:55 sbs-pf2 python[4734]: sqlalchemy.exc.NoResultFound: No row was found when one was required
```
If possible, include some more info about the invitation (e.g., was it already accpeted, by whom, etc)

**Comment by oharsta** [comment]
This exception is thrown if the invitation can not be found and is raised by SQLAlchemy. As the invitation is not found, there is not much to log about the invitation. Also the exception is caught client-side and therefore has to be thrown. 404's are generic logged in general so suppressing the stack-trace would be done for all 404's. Recommendation is not to alter the current behaviour.

**Comment by baszoetekouw** [comment]
fair enough
