### ISSUE TITLE
toch weer iets mis mis met image cache

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#481]
```
Jan 19 13:03:56 sbs-pf2 python[4734]: [2023-01-19 13:03:56,375] ERROR in app: Exception on /api/images/collaborations/9c21effb-377a-4051-8ef0-b63cf216c25e [GET]
Jan 19 13:03:56 sbs-pf2 python[4734]: Traceback (most recent call last):
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
Jan 19 13:03:56 sbs-pf2 python[4734]:     response = self.full_dispatch_request()
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
Jan 19 13:03:56 sbs-pf2 python[4734]:     rv = self.handle_user_exception(e)
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
Jan 19 13:03:56 sbs-pf2 python[4734]:     rv = self.dispatch_request()
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
Jan 19 13:03:56 sbs-pf2 python[4734]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/opt/sbs/sbs/server/api/image.py", line 14, in get_logo
Jan 19 13:03:56 sbs-pf2 python[4734]:     decoded_logo = base64.decodebytes(logo)
Jan 19 13:03:56 sbs-pf2 python[4734]:   File "/usr/lib/python3.9/base64.py", line 538, in decodebytes
Jan 19 13:03:56 sbs-pf2 python[4734]:     return binascii.a2b_base64(s)
Jan 19 13:03:56 sbs-pf2 python[4734]: binascii.Error: Incorrect padding
```

**Comment by baszoetekouw** [comment]
Lijkt nu alleen nog mis te gaan bij collaboration requests.  Die hebben weer een url in `collaboration.logo` .

Kan zijn dat deze bug inmiddels ook is gefixed, want de getroffen CO's zijn in sep 2022 aangemaakt,

**Comment by FlorisFokkinga** [comment]
Has not been reported since.
