### ISSUE TITLE
SCIM error propagation

### ISSUE THREAD

**Issue by oharsta** [SURFscz/SBS#519]
Any exceptions raised in the SCIM events are swallowed and stack-traces are not logged. This makes trouble-shooting almost impossible. Either find a way to propagate exceptions are except and exception thrown and explicitly log them including stack-traces

**Comment by oharsta** [comment]
https://github.com/dchevell/flask-executor/issues/24

**Comment by HarryKodden** [comment]
Fouten komen nu netjes in de journal. Bijvoorbeeld bij een onbereikbare remote SCIM server zie je melding als deze:

```
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:17 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl returned an error: {}
Mar 14 14:32:18 sbs-af2 python[2454]: ERROR [base] user: 72e8fabfeca6a933d2eb97dc96053f10dc49fd8d@acc.sram.eduteams.org, <Response 66 bytes [500 INTERNAL SERVER ERROR]>
Mar 14 14:32:18 sbs-af2 python[2454]: Traceback (most recent call last):
Mar 14 14:32:18 sbs-af2 python[2454]:   File "/opt/sbs/sbs/server/api/base.py", line 161, in wrapper
Mar 14 14:32:18 sbs-af2 python[2454]:     body, status = f(*args, **kwargs)
Mar 14 14:32:18 sbs-af2 python[2454]:   File "/opt/sbs/sbs/server/api/scim.py", line 144, in sweep
Mar 14 14:32:18 sbs-af2 python[2454]:     return perform_sweep(service), 201
Mar 14 14:32:18 sbs-af2 python[2454]:   File "/opt/sbs/sbs/server/scim/sweep.py", line 184, in perform_sweep
Mar 14 14:32:18 sbs-af2 python[2454]:     membership_scim_objects = _memberships(group, remote_users_by_external_id)
Mar 14 14:32:18 sbs-af2 python[2454]:   File "/opt/sbs/sbs/server/scim/sweep.py", line 100, in _memberships
Mar 14 14:32:18 sbs-af2 python[2454]:     scim_object = remote_users_by_external_id[member.user.external_id]
Mar 14 14:32:18 sbs-af2 python[2454]: KeyError: 'b0ec1a48-9dff-4b77-af3d-ff3a4c453ffc'
Mar 14 14:32:18 sbs-af2 python[2454]: DEBUG [user] user: 72e8fabfeca6a933d2eb97dc96053f10dc49fd8d@acc.sram.eduteams.org, Sending mail message to sram-logs@surf.nl with Message-id <797925a7.bd3e.4ec5.ac7b.fec1646cc034@sbs.af2.internal.sram.surf.nl>
```

**Comment by HarryKodden** [comment]
daarmee is in principe voldaan aan issue en kunnen we deze deployen
