### ISSUE TITLE
SCIM KeyError: 'externalId'

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#531]
```
Feb 23 13:00:10 sbs-pf1 python[9156]: ERROR [apscheduler.executors.default] Job "scim_sweep_services (trigger: cron[day='*', hour='*', minute='*/15'], next run at: 2023-02-23 13:15:00 UTC)" raised an exception
Feb 23 13:00:10 sbs-pf1 python[9156]: Traceback (most recent call last):
Feb 23 13:00:10 sbs-pf1 python[9156]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
Feb 23 13:00:10 sbs-pf1 python[9156]:     retval = job.func(*job.args, **job.kwargs)
Feb 23 13:00:10 sbs-pf1 python[9156]:   File "/opt/sbs/sbs/server/cron/scim_sweep_services.py", line 51, in scim_sweep_services
Feb 23 13:00:10 sbs-pf1 python[9156]:     return obtain_lock(app, scim_sweep_services_lock_name, _do_scim_sweep_services, _result_container)
Feb 23 13:00:10 sbs-pf1 python[9156]:   File "/opt/sbs/sbs/server/cron/shared.py", line 14, in obtain_lock
Feb 23 13:00:10 sbs-pf1 python[9156]:     return success(app) if lock_obtained else failure()
Feb 23 13:00:10 sbs-pf1 python[9156]:   File "/opt/sbs/sbs/server/cron/scim_sweep_services.py", line 38, in _do_scim_sweep_services
Feb 23 13:00:10 sbs-pf1 python[9156]:     sync_results = perform_sweep(service)
Feb 23 13:00:10 sbs-pf1 python[9156]:   File "/opt/sbs/sbs/server/scim/sweep.py", line 139, in perform_sweep
Feb 23 13:00:10 sbs-pf1 python[9156]:     if f"{remote_user['externalId'].replace(EXTERNAL_ID_POST_FIX, '')}" not in users_by_external_id:
Feb 23 13:00:10 sbs-pf1 python[9156]: KeyError: 'externalId'
```

**Comment by oharsta** [comment]
The SRAM code should be more defensive. This is corrected in https://github.com/SURFscz/SBS/commit/7974722ac1ba1a8740eb409a0ed97e706ab33332. But the external SCIM interface must include the externalId

**Comment by FlorisFokkinga** [comment]
No reproduction steps, no more recent occurences reported.
