### ISSUE TITLE
"TimeoutError: QueuePool limit of size 10 overflow 10 reached"

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#537]
@oharsta do you hav any idea of what could be causing this?  The `haproxy_url` user queries `/api/plsc/ip_ranges` every minute or so; that hasn't resulted in any error until now:

```
Bad news. An error occurred in acc.sram.surf.nl at 2023-02-26 23:31:28.752603 for user haproxy_acl:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 156, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/plsc.py", line 153, in ip_ranges
    data = IpNetwork.query.all()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
```

**Comment by oharsta** [comment]
Added db.session.close as a finally statement in both all normal API endpoints and the SCIM events. The error has not occurred anymore on test after this changes were deployed. See https://github.com/SURFscz/SBS/commit/105031917195cbf241afb4bff4feccfd19c2192a
