### ISSUE TITLE
Org API returns 500 instead of 403 when permission denied

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#547]
When querying the org api for a collaboration with a token that belongs to a different org (or to a service), the API returns a 500 and throws this stack trace:

```
Mar 07 14:23:34 app1-tf1 python[1232378]: Traceback (most recent call last):
Mar 07 14:23:34 app1-tf1 python[1232378]:   File "/opt/sbs/sbs/server/api/base.py", line 161, in wrapper
Mar 07 14:23:34 app1-tf1 python[1232378]:     body, status = f(*args, **kwargs)
Mar 07 14:23:34 app1-tf1 python[1232378]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 110, in api_collaboration_by_identifier
Mar 07 14:23:34 app1-tf1 python[1232378]:     if organisation.id != collaboration.organisation_id:
Mar 07 14:23:34 app1-tf1 python[1232378]: AttributeError: 'NoneType' object has no attribute 'id'
```

Instead, it should result in a 403.

**Comment by baszoetekouw** [comment]
confirmed
