### ISSUE TITLE
error: circular reference detected

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#600]
```
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 167, in wrapper
    response = jsonify(body)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

Als reactie op een POST naar `https://sram.surf.nl/api/collaborations`

**Comment by oharsta** [comment]
@baszoetekouw I can't reproduce this. Can you reproduce this on test and attach the details of the payload and the organisation in which you created this CO to this issue.

**Comment by baszoetekouw** [comment]
Kan het niet reproduceren, en is afgelopen maand niet meer opgetreden.
