### ISSUE TITLE
Please don't send error mail about failed CO creationg via API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#610]
```
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 166, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/collaboration.py", line 505, in save_collaboration_api
    res = do_save_collaboration(data, organisation, user, current_user_admin=False, save_tags=False)
  File "/opt/sbs/sbs/server/api/collaboration.py", line 518, in do_save_collaboration
    _validate_collaboration(data, organisation)
  File "/opt/sbs/sbs/server/api/collaboration.py", line 589, in _validate_collaboration
    raise BadRequest(f"Collaboration with name '{data['name']}' already exists within "
werkzeug.exceptions.BadRequest: 400 Bad Request: BadRequest: http://sram.surf.nl/api/collaborations/v1. IP: 20.23.x.y, 10.0.0.20. Collaboration with name 'XXXX' already exists within organisation 'Universiteit XXX'.
```

**Comment by baszoetekouw** [comment]
works correctly now.
