### ISSUE TITLE
Gracefully handle SCIM timeouts

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#612]
When a remote SCIm server timeouts, this leads to an ugly error message:

```
{"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", "message": "Uncaught Error", "url": "https://sram.surf.nl/static/js/main.0ddf2e82.js", "line": 2, "col": 2223652, "error": "", "stack": "Error\n    at https://sram.surf.nl/static/js/main.0ddf2e82.js:2:2223523", "targetUrl": "https://sram.surf.nl/api/scim/v2/sweep?service_id=77", "status": 500}
```
and
```
Traceback (most recent call last):
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/green/ssl.py", line 253, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/green/ssl.py", line 268, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/green/ssl.py", line 187, in read
    return self._call_trampolining(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/green/ssl.py", line 165, in _call_trampolining
    trampoline(self,
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/eventlet/hubs/hub.py", line 313, in switch
    return self.greenlet.switch()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='scim.exp.sram.lab.surf.nl', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 166, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/scim.py", line 144, in sweep
    return perform_sweep(service), 201
  File "/opt/sbs/sbs/server/scim/sweep.py", line 133, in perform_sweep
    remote_scim_groups = _all_remote_scim_objects(service, SCIM_GROUPS)
  File "/opt/sbs/sbs/server/scim/sweep.py", line 91, in _all_remote_scim_objects
    response = requests.get(url, headers=scim_headers(service), timeout=10)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='scim.exp.sram.lab.surf.nl', port=443): Read timed out. (read timeout=10)
```
Can we handle this more gracefully?  I.e., catch the exception, return a descriptive error to the API call, and don't send an amail to -logs.

**Comment by HarryKodden** [comment]
The frontend (System / SCIM / Sweep) times out and does not throw error
The backend shows messages like this: ERROR [scim] Scim endpoint https://scim.exp.sram.lab.surf.nl/api/v4 returned an error: {}
Looks OK
