### ISSUE TITLE
SCIM error

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#613]
I'm seeing multiple of these errors:
```
{"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", "message": "Uncaught Error", "url": "https://sram.surf.nl/static/js/main.0ddf2e82.js", "line": 2, "col": 2223652, "error": "", "stack": "Error\n    at https://sram.surf.nl/static/js/main.0ddf2e82.js:2:2223523", "targetUrl": "https://sram.surf.nl/api/scim/v2/sweep?service_id=77", "status": 500}
```

```
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 166, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/scim.py", line 144, in sweep
    return perform_sweep(service), 201
  File "/opt/sbs/sbs/server/scim/sweep.py", line 193, in perform_sweep
    membership_scim_objects = _memberships(group, remote_users_by_external_id)
  File "/opt/sbs/sbs/server/scim/sweep.py", line 109, in _memberships
    scim_object = remote_users_by_external_id[member.user.external_id]
KeyError: '3e12045a-f9a7-46d6-aeba-d3e7ae5d0459'
```

Can we handle this more gracefully?  If the remote server is at fault, we should give feedback of this to the user.

**Comment by baszoetekouw** [comment]
@HarryKodden is triggering these issues btw, in case you need to reproduce them.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/82ca9207bc8245e350dcf4ab316ccbe6dc6c4715#diff-0515ef78674a8f6154a13834c9ad0bdb9f07e17b51b7641b6ac095f76a184e77R109

**Comment by HarryKodden** [comment]
OK !
