### ISSUE TITLE
Internal server error when using an unknown API key

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#624]
When using an unknown API key for the organization API, SBS returns an error 500 "'NoneType' object has no attribute 'organisation_memberships'"
```
Apr 12 11:40:28 app1-tf1 python[2080185]: ERROR [base] user: 9bf251bf6cfa9eb8c75f15a90075fa7074eb3d48@acc.sram.eduteams.org, <Response 89 bytes [500 INTERNAL SERVER ERROR]>
Apr 12 11:40:28 app1-tf1 python[2080185]: Traceback (most recent call last):
Apr 12 11:40:28 app1-tf1 python[2080185]:   File "/opt/sbs/sbs/server/api/base.py", line 167, in wrapper
Apr 12 11:40:28 app1-tf1 python[2080185]:     body, status = f(*args, **kwargs)
Apr 12 11:40:28 app1-tf1 python[2080185]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 487, in save_collaboration_api
Apr 12 11:40:28 app1-tf1 python[2080185]:     admins = list(filter(lambda mem: mem.role == "admin", organisation.organisation_memberships))
Apr 12 11:40:28 app1-tf1 python[2080185]: AttributeError: 'NoneType' object has no attribute 'organisation_memberships'
```

Instead, it should simply return a 403.

**Comment by oharsta** [comment]
This is only reproducible (and fixed) if there is both a user in the session and an authorization header and the swagger_is_enabled is true. E.g. playing with swagger on the test environment;-)

**Comment by baszoetekouw** [comment]
tested.
