### ISSUE TITLE
Unexpected error when removing a CO from a Service 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#632]
When removing a CO from a Service as a Service admin, I get the following screen:
![Screenshot 2023-04-19 at 16 38 13](https://user-images.githubusercontent.com/1461740/233110798-5cdc89bc-b041-4a6c-9168-d6ac5c4f6fea.png)
```
Apr 19 14:40:52 sbs-af1 python[68923]: ERROR [scim] Error in applying SCIM change
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     conn = connection.create_connection(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
Apr 19 14:40:52 sbs-af1 python[68923]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
Apr 19 14:40:52 sbs-af1 python[68923]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Apr 19 14:40:52 sbs-af1 python[68923]: socket.gaierror: [Errno -2] Name or service not known
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Apr 19 14:40:52 sbs-af1 python[68923]:     httplib_response = self._make_request(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
Apr 19 14:40:52 sbs-af1 python[68923]:     self._validate_conn(conn)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     conn.connect()
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
Apr 19 14:40:52 sbs-af1 python[68923]:     self.sock = conn = self._new_conn()
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     raise NewConnectionError(
Apr 19 14:40:52 sbs-af1 python[68923]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     resp = conn.urlopen(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
Apr 19 14:40:52 sbs-af1 python[68923]:     retries = retries.increment(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
Apr 19 14:40:52 sbs-af1 python[68923]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Apr 19 14:40:52 sbs-af1 python[68923]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.zoetekouw.net', port=443): Max retries exceeded with url: /scim/Groups?filter=externalId%20eq%20%2289f79f14-475c-4b07-abb8-93a9f9f5ae9d%40sram.surf.nl%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 27, in wrapper
Apr 19 14:40:52 sbs-af1 python[68923]:     res = f(*args, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 239, in apply_service_changed
Apr 19 14:40:52 sbs-af1 python[68923]:     results = [_do_apply_group_collaboration_change(group, services, deletion) for group in collaboration.groups]
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 239, in <listcomp>
Apr 19 14:40:52 sbs-af1 python[68923]:     results = [_do_apply_group_collaboration_change(group, services, deletion) for group in collaboration.groups]
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 164, in _do_apply_group_collaboration_change
Apr 19 14:40:52 sbs-af1 python[68923]:     scim_object = _lookup_scim_object(service, SCIM_GROUPS, group.identifier)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 124, in _lookup_scim_object
Apr 19 14:40:52 sbs-af1 python[68923]:     response = requests.get(url, headers=scim_headers(service), timeout=10)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 73, in get
Apr 19 14:40:52 sbs-af1 python[68923]:     return request("get", url, params=params, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 59, in request
Apr 19 14:40:52 sbs-af1 python[68923]:     return session.request(method=method, url=url, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
Apr 19 14:40:52 sbs-af1 python[68923]:     resp = self.send(prep, **send_kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     r = adapter.send(request, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     raise ConnectionError(e, request=request)
Apr 19 14:40:52 sbs-af1 python[68923]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.zoetekouw.net', port=443): Max retries exceeded with url: /scim/Groups?filter=externalId%20eq%20%2289f79f14-475c-4b07-abb8-93a9f9f5ae9d%40sram.surf.nl%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Apr 19 14:40:52 sbs-af1 python[68923]: ERROR [base] user: 9bf251bf6cfa9eb8c75f15a90075fa7074eb3d48@acc.sram.eduteams.org, <Response 383 bytes [500 INTERNAL SERVER ERROR]>
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     conn = connection.create_connection(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
Apr 19 14:40:52 sbs-af1 python[68923]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
Apr 19 14:40:52 sbs-af1 python[68923]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Apr 19 14:40:52 sbs-af1 python[68923]: socket.gaierror: [Errno -2] Name or service not known
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
Apr 19 14:40:52 sbs-af1 python[68923]:     httplib_response = self._make_request(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
Apr 19 14:40:52 sbs-af1 python[68923]:     self._validate_conn(conn)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     conn.connect()
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
Apr 19 14:40:52 sbs-af1 python[68923]:     self.sock = conn = self._new_conn()
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
Apr 19 14:40:52 sbs-af1 python[68923]:     raise NewConnectionError(
Apr 19 14:40:52 sbs-af1 python[68923]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     resp = conn.urlopen(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
Apr 19 14:40:52 sbs-af1 python[68923]:     retries = retries.increment(
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
Apr 19 14:40:52 sbs-af1 python[68923]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Apr 19 14:40:52 sbs-af1 python[68923]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.zoetekouw.net', port=443): Max retries exceeded with url: /scim/Groups?filter=externalId%20eq%20%2289f79f14-475c-4b07-abb8-93a9f9f5ae9d%40sram.surf.nl%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Apr 19 14:40:52 sbs-af1 python[68923]: During handling of the above exception, another exception occurred:
Apr 19 14:40:52 sbs-af1 python[68923]: Traceback (most recent call last):
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/api/base.py", line 167, in wrapper
Apr 19 14:40:52 sbs-af1 python[68923]:     body, status = f(*args, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/api/collaborations_services.py", line 125, in delete_collaborations_services
Apr 19 14:40:52 sbs-af1 python[68923]:     broadcast_service_deleted(collaboration.id, service.id)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/events.py", line 16, in wrapper
Apr 19 14:40:52 sbs-af1 python[68923]:     return f(*args, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/events.py", line 73, in broadcast_service_deleted
Apr 19 14:40:52 sbs-af1 python[68923]:     return current_app.sync_executor.submit(apply_service_changed, current_app, collaboration_id, service_id, True)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/db/executor.py", line 7, in submit
Apr 19 14:40:52 sbs-af1 python[68923]:     return fn(*args, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 34, in wrapper
Apr 19 14:40:52 sbs-af1 python[68923]:     raise e
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 27, in wrapper
Apr 19 14:40:52 sbs-af1 python[68923]:     res = f(*args, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 239, in apply_service_changed
Apr 19 14:40:52 sbs-af1 python[68923]:     results = [_do_apply_group_collaboration_change(group, services, deletion) for group in collaboration.groups]
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 239, in <listcomp>
Apr 19 14:40:52 sbs-af1 python[68923]:     results = [_do_apply_group_collaboration_change(group, services, deletion) for group in collaboration.groups]
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 164, in _do_apply_group_collaboration_change
Apr 19 14:40:52 sbs-af1 python[68923]:     scim_object = _lookup_scim_object(service, SCIM_GROUPS, group.identifier)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs/server/scim/scim.py", line 124, in _lookup_scim_object
Apr 19 14:40:52 sbs-af1 python[68923]:     response = requests.get(url, headers=scim_headers(service), timeout=10)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 73, in get
Apr 19 14:40:52 sbs-af1 python[68923]:     return request("get", url, params=params, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/api.py", line 59, in request
Apr 19 14:40:52 sbs-af1 python[68923]:     return session.request(method=method, url=url, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
Apr 19 14:40:52 sbs-af1 python[68923]:     resp = self.send(prep, **send_kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     r = adapter.send(request, **kwargs)
Apr 19 14:40:52 sbs-af1 python[68923]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
Apr 19 14:40:52 sbs-af1 python[68923]:     raise ConnectionError(e, request=request)
Apr 19 14:40:52 sbs-af1 python[68923]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.zoetekouw.net', port=443): Max retries exceeded with url: /scim/Groups?filter=externalId%20eq%20%2289f79f14-475c-4b07-abb8-93a9f9f5ae9d%40sram.surf.nl%22 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fae888e38e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Apparent this is caused by a misconfigured or non-responding SCIM server.  

We should probably show the Service admin an error notification, but it should not be fatal.

**Comment by oharsta** [comment]
@baszoetekouw We currently have two executors for sending SCIM messages. One that sends SCIM messages async in a separate thread, these are all the PUT's and POSTS's, and one executor that uses the main thread, these are the DELETE operations. The DELETE operations can not be run async, because the information would be gone from the database after the actual delete of the object. Error messages in the async executor are propagated and therefore logged, but do not reach the client due to the nature of async execution. The async and sync executor shared the same error propagation and therefore the SCIM error ended up at the client. This has been changed and errors that occur in the sync executor are logged, but not end up in the client. 

Due to the generic behaviour of the SCIM messaging and the many places where those are called, we should not differentiate in the error handling. Because the action that lead to a SCIM message - in this case removing a CO from a Service - is correctly executed. The same applies when adding a group to a CO: if this is successful, but sending the subsequent SCIM message failed, then we don't want to show this as an error to the CO admin who created the group.

**Comment by FlorisFokkinga** [comment]
This is still reproducable.

![Image](https://user-images.githubusercontent.com/80269262/236782159-4493fed5-e6e8-4d8a-a56b-5045c1710087.png)

**Comment by oharsta** [comment]
@FlorisFokkinga Can you add the service and CO with which you could reproduce this on the test environment to this issue? I can't reproduce this locally.

**Comment by FlorisFokkinga** [comment]
I cannot reproduce this at the moment. I don't remember exactly what I did.
@baszoetekouw, is there a log that can help us here?

**Comment by baszoetekouw** [comment]
No, these are frontend errors which we cannot easily see in the logs.  Let's close htis issue for now.
