### ISSUE TITLE
Monitor if locale files of all languages have identitcal attributes and structure

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#655]
- To easily spot forgotten translations
- The same structure makes it easier to edit multiple languages a the same time

**Comment by baszoetekouw** [comment]
The SBS client tests already check that the structure of the locales are identical.  Issiue to solve here is that for translators it is very convenient if the line number of the different locale files correctspond to the same translation key.

So maybe just add some automation to reformat/resort the locale files?

**Comment by baszoetekouw** [comment]
Failures in the ordering of the transltion keys now show as:
```
 FAIL  src/__tests__/locale/en.test.js
  ● All translations exists in all bundles

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 2

      28 |     contains(nl, en, keyCollectionNL);
      29 |     const positionalMismatches = keyCollectionEN.filter((item, index) => keyCollectionNL[index] !== item);
    > 30 |     expect(positionalMismatches.length).toEqual(0)
         |                                         ^
      31 | });

      at Object.<anonymous> (src/__tests__/locale/en.test.js:30:41)

 PASS  src/__tests__/utils/Stats.test.js
 PASS  src/__tests__/utils/Markdown.test.js
 PASS  src/__tests__/validations/regExp.test.js
 PASS  src/__tests__/utils/Utils.test.js
 PASS  src/__tests__/utils/Date.test.js

Test Suites: 1 failed, 7 passed, 8 total
Tests:       1 failed, 25 passed, 26 total
Snapshots:   0 total
Time:        1.754 s
Ran all test suites.

Watch Usage: Press w to show more.
```
I've improved the test a little bit in https://github.com/SURFscz/SBS/commit/f6cd9273d0c6ef3b94ec104a85b5701318a3a2dc to make the output more traceble.  A failed test now outputs:
```
 FAIL  src/__tests__/locale/en.test.js
  ● All translations exists in all bundles

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 4

    - Array []
    + Array [
    +   "breadcrumb.organisations",
    +   "breadcrumb.organisation",
    + ]

      28 |     contains(nl, en, keyCollectionNL, '');
      29 |     const positionalMismatches = keyCollectionEN.filter((item, index) => keyCollectionNL[index] !== item);
    > 30 |     expect(positionalMismatches).toEqual([])
         |                                  ^
      31 | });

      at Object.<anonymous> (src/__tests__/locale/en.test.js:30:34)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       1 failed, 25 passed, 26 total
Snapshots:   0 total
Time:        1.628 s, estimated 2 s
Ran all test suites.
```
