### ISSUE TITLE
Cannot delete CO via the API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#746]
```
╰─▶ curl -X GET "https://acc.sram.surf.nl/api/collaborations/v1/d0aee9b6-13a5-463e-85b4-5297d007649a" -H  "accept: application/json" -H  "Authorization: Bearer Abcde"
{"accepted_user_policy":null,"collaboration_memberships":[{"collaboration_id":106,"created_at":1685617315,"created_by":"xxx@acc.sram.eduteams.org","expiry_date":null,"id":222,"invitation_id":null,"role":"admin","status":"active","updated_by":"xxx@acc.sram.eduteams.org","user":{"address":null,"affiliation":"member@acc.sram.eduteams.org","application_uid":null,"created_at":1596189179,"created_by":"9xxx@acc.sram.eduteams.org","edu_members":null,"eduperson_principal_name":"bas@surfnet.nl","email":"bas.zoetekouw@surf.nl","entitlement":"urn:geant:eduteams.org:acc.sram.eduteams.org:group:surf-ram#acc.sram.eduteams.org","external_id":"b0ec1a48-9dff-4b77-af3d-ff3a4c453ffc","family_name":"Zoetekouw","given_name":"Bas","home_organisation_uid":"bas","id":1,"last_accessed_date":1683723793,"last_login_date":1685616523,"mfa_reset_token":null,"name":"Bas Zoetekouw","nick_name":null,"pam_last_login_date":null,"schac_home_organisation":"surfnet.nl","scoped_affiliation":"employee@surfnet.nl","second_fa_uuid":"bba684de-097e-41cd-9de1-dc94e743ef1f","second_factor_auth":null,"ssh_keys":[],"ssid_required":false,"suspended":false,"uid":"xxx@acc.sram.eduteams.org","updated_at":1685616523,"updated_by":"xxx@acc.sram.eduteams.org","user_ip_networks":[],"username":"bzoetekouw"},"user_id":1}],"collaboration_memberships_count":1,"created_at":1685617315,"created_by":"9bf2xxx@acc.sram.eduteams.org","description":"api test delete","disable_join_requests":true,"disclose_email_information":true,"disclose_member_information":true,"expiry_date":null,"global_urn":"uniharderwijk:bastest1","groups":[],"id":106,"identifier":"d0aee9b6-13a5-463e-85b4-5297d007649a","invitations_count":0,"last_activity_date":1685617315,"logo":"https://acc.sram.surf.nl/api/images/collaborations/1747caeb-f986-4d92-a834-31208f87ec31","name":"Bas test 1","organisation_id":21,"services":[],"short_name":"bastest1","status":"active","tags":[{"id":50,"tag_value":"label_1"}],"updated_at":1685617315,"updated_by":"xxx@acc.sram.eduteams.org","uuid4":"1747caeb-f986-4d92-a834-31208f87ec31","website_url":"https://research.uniharderwijk.nl/cumulusgrp"}

╰─▶ curl -X DELETE "https://acc.sram.surf.nl/api/collaborations/v1/d0aee9b6-13a5-463e-85b4-5297d007649a" -H  "accept: application/json" -H  "Authorization: Bearer Abcde"
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

stacktrace:
```
Jun 01 11:09:42 sbs-af1 python[294162]: INFO  [external_api] Authorized API call for organisation University of Harderwijk with key bas test mag weg
Jun 01 11:09:43 sbs-af1 python[294162]: ERROR [base] user: ext_api, <Response 201 bytes [500 INTERNAL SERVER ERROR]>
Jun 01 11:09:43 sbs-af1 python[294162]: Traceback (most recent call last):
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     body, status = f(*args, **kwargs)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 130, in delete_collaboration_api
Jun 01 11:09:43 sbs-af1 python[294162]:     return delete(Collaboration, collaboration.id)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 11:09:43 sbs-af1 python[294162]:     return object.__getattribute__(self, name)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 11:09:43 sbs-af1 python[294162]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 11:09:43 sbs-af1 python[294162]:     return state._load_expired(state, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 11:09:43 sbs-af1 python[294162]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 11:09:43 sbs-af1 python[294162]:     raise orm_exc.DetachedInstanceError(
Jun 01 11:09:43 sbs-af1 python[294162]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7f27bb219f40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Jun 01 11:09:43 sbs-af1 python[294162]: [2023-06-01 11:09:43,620] ERROR in app: Exception on /api/collaborations/v1/d0aee9b6-13a5-463e-85b4-5297d007649a [DELETE]
Jun 01 11:09:43 sbs-af1 python[294162]: Traceback (most recent call last):
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     body, status = f(*args, **kwargs)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 130, in delete_collaboration_api
Jun 01 11:09:43 sbs-af1 python[294162]:     return delete(Collaboration, collaboration.id)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 11:09:43 sbs-af1 python[294162]:     return object.__getattribute__(self, name)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 11:09:43 sbs-af1 python[294162]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 11:09:43 sbs-af1 python[294162]:     return state._load_expired(state, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 11:09:43 sbs-af1 python[294162]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 11:09:43 sbs-af1 python[294162]:     raise orm_exc.DetachedInstanceError(
Jun 01 11:09:43 sbs-af1 python[294162]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7f27bb219f40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Jun 01 11:09:43 sbs-af1 python[294162]: During handling of the above exception, another exception occurred:
Jun 01 11:09:43 sbs-af1 python[294162]: Traceback (most recent call last):
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
Jun 01 11:09:43 sbs-af1 python[294162]:     response = self.full_dispatch_request()
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     rv = self.handle_user_exception(e)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     rv = self.dispatch_request()
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flasgger/utils.py", line 305, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     return function(*args, **kwargs)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 205, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     send_error_mail(tb=traceback.format_exc())
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 145, in send_error_mail
Jun 01 11:09:43 sbs-af1 python[294162]:     user_id = f"Organisation API call {request_context.get('external_api_organisation').name}"
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 11:09:43 sbs-af1 python[294162]:     return object.__getattribute__(self, name)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 11:09:43 sbs-af1 python[294162]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 11:09:43 sbs-af1 python[294162]:     return state._load_expired(state, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 11:09:43 sbs-af1 python[294162]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 11:09:43 sbs-af1 python[294162]:     raise orm_exc.DetachedInstanceError(
Jun 01 11:09:43 sbs-af1 python[294162]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Organisation at 0x7f27bb1ff8b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Jun 01 11:09:43 sbs-af1 python[294162]: ERROR [__main__] Exception on /api/collaborations/v1/d0aee9b6-13a5-463e-85b4-5297d007649a [DELETE]
Jun 01 11:09:43 sbs-af1 python[294162]: Traceback (most recent call last):
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     body, status = f(*args, **kwargs)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 130, in delete_collaboration_api
Jun 01 11:09:43 sbs-af1 python[294162]:     return delete(Collaboration, collaboration.id)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 11:09:43 sbs-af1 python[294162]:     return object.__getattribute__(self, name)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 11:09:43 sbs-af1 python[294162]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 11:09:43 sbs-af1 python[294162]:     return state._load_expired(state, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 11:09:43 sbs-af1 python[294162]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 11:09:43 sbs-af1 python[294162]:     raise orm_exc.DetachedInstanceError(
Jun 01 11:09:43 sbs-af1 python[294162]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7f27bb219f40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Jun 01 11:09:43 sbs-af1 python[294162]: During handling of the above exception, another exception occurred:
Jun 01 11:09:43 sbs-af1 python[294162]: Traceback (most recent call last):
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
Jun 01 11:09:43 sbs-af1 python[294162]:     response = self.full_dispatch_request()
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     rv = self.handle_user_exception(e)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     rv = self.dispatch_request()
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flasgger/utils.py", line 305, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     return function(*args, **kwargs)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 205, in wrapper
Jun 01 11:09:43 sbs-af1 python[294162]:     send_error_mail(tb=traceback.format_exc())
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/api/base.py", line 145, in send_error_mail
Jun 01 11:09:43 sbs-af1 python[294162]:     user_id = f"Organisation API call {request_context.get('external_api_organisation').name}"
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 11:09:43 sbs-af1 python[294162]:     return object.__getattribute__(self, name)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 11:09:43 sbs-af1 python[294162]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 11:09:43 sbs-af1 python[294162]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 11:09:43 sbs-af1 python[294162]:     return state._load_expired(state, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 11:09:43 sbs-af1 python[294162]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 11:09:43 sbs-af1 python[294162]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 11:09:43 sbs-af1 python[294162]:     raise orm_exc.DetachedInstanceError(
Jun 01 11:09:43 sbs-af1 python[294162]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Organisation at 0x7f27bb1ff8b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/a82f2910bbbd4db923923277b91b868698cac128

**Comment by baszoetekouw** [comment]
I still get en error 500:
```
Jun 01 13:27:20 sbs-af1 python[306727]: ERROR [base] user: ext_api, <Response 201 bytes [500 INTERNAL SERVER ERROR]>
Jun 01 13:27:20 sbs-af1 python[306727]: Traceback (most recent call last):
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Jun 01 13:27:20 sbs-af1 python[306727]:     body, status = f(*args, **kwargs)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 130, in delete_collaboration_api
Jun 01 13:27:20 sbs-af1 python[306727]:     return delete(Collaboration, collaboration.id)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs/server/db/logo_mixin.py", line 64, in __getattribute__
Jun 01 13:27:20 sbs-af1 python[306727]:     return object.__getattribute__(self, name)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
Jun 01 13:27:20 sbs-af1 python[306727]:     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1084, in get
Jun 01 13:27:20 sbs-af1 python[306727]:     value = self._fire_loader_callables(state, key, passive)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1114, in _fire_loader_callables
Jun 01 13:27:20 sbs-af1 python[306727]:     return state._load_expired(state, passive)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
Jun 01 13:27:20 sbs-af1 python[306727]:     self.manager.expired_attribute_loader(self, toload, passive)
Jun 01 13:27:20 sbs-af1 python[306727]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1558, in load_scalar_attributes
Jun 01 13:27:20 sbs-af1 python[306727]:     raise orm_exc.DetachedInstanceError(
Jun 01 13:27:20 sbs-af1 python[306727]: sqlalchemy.orm.exc.DetachedInstanceError: Instance <Collaboration at 0x7fbcc8b2cb80> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```

**Comment by baszoetekouw** [comment]
Er is nog steeds iets mis: de error is nu veranderd in:
```
Jun 01 15:03:21 sbs-af1 python[307672]: INFO  [external_api] Authorized API call for organisation University of Harderwijk with key bas test mag weg
Jun 01 15:03:22 sbs-af1 python[307672]: ERROR [base] user: ext_api, <Response 124 bytes [500 INTERNAL SERVER ERROR]>
Jun 01 15:03:22 sbs-af1 python[307672]: Traceback (most recent call last):
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Jun 01 15:03:22 sbs-af1 python[307672]:     body, status = f(*args, **kwargs)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 131, in delete_collaboration_api
Jun 01 15:03:22 sbs-af1 python[307672]:     return delete(Collaboration, collaboration_id)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs/server/db/models.py", line 102, in delete
Jun 01 15:03:22 sbs-af1 python[307672]:     db.session.commit()
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 553, in commit
Jun 01 15:03:22 sbs-af1 python[307672]:     return self._proxied.commit()
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1905, in commit
Jun 01 15:03:22 sbs-af1 python[307672]:     trans.commit(_to_root=True)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "<string>", line 2, in commit
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
Jun 01 15:03:22 sbs-af1 python[307672]:     ret_value = fn(self, *arg, **kw)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1220, in commit
Jun 01 15:03:22 sbs-af1 python[307672]:     self._prepare_impl()
Jun 01 15:03:22 sbs-af1 python[307672]:   File "<string>", line 2, in _prepare_impl
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
Jun 01 15:03:22 sbs-af1 python[307672]:     ret_value = fn(self, *arg, **kw)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1195, in _prepare_impl
Jun 01 15:03:22 sbs-af1 python[307672]:     self.session.flush()
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4153, in flush
Jun 01 15:03:22 sbs-af1 python[307672]:     self._flush(objects)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4290, in _flush
Jun 01 15:03:22 sbs-af1 python[307672]:     transaction.rollback(_capture_exception=True)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
Jun 01 15:03:22 sbs-af1 python[307672]:     raise exc_value.with_traceback(exc_tb)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4250, in _flush
Jun 01 15:03:22 sbs-af1 python[307672]:     flush_context.execute()
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
Jun 01 15:03:22 sbs-af1 python[307672]:     rec.execute(self)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 591, in execute
Jun 01 15:03:22 sbs-af1 python[307672]:     self.dependency_processor.process_deletes(uow, states)
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/dependency.py", line 1114, in process_deletes
Jun 01 15:03:22 sbs-af1 python[307672]:     self._run_crud(
Jun 01 15:03:22 sbs-af1 python[307672]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/dependency.py", line 1211, in _run_crud
Jun 01 15:03:22 sbs-af1 python[307672]:     raise exc.StaleDataError(
Jun 01 15:03:22 sbs-af1 python[307672]: sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'collaboration_tags' expected to delete 1 row(s); Only 2 were matched.
```
