### ISSUE TITLE
Added CO with invalid logo from API gives error 500

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#849]
When added a CO via the Org Api, and the specified CO has a logo url that cannot be reached, an internal server error is triggered:

```
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]: ERROR [base] user: ext_api, <Response 53 bytes [500 INTERNAL SERVER ERROR]>
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]: Traceback (most recent call last):
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     body, status = f(*args, **kwargs)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/opt/sbs/sbs/server/api/collaboration.py", line 511, in save_collaboration_api
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     res = urllib.request.urlopen(logo)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     return opener.open(url, data, timeout)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 523, in open
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     response = meth(req, response)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     response = self.parent.error(
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 561, in error
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     return self._call_chain(*args)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     result = func(*args)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:   File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
Aug 03 09:00:09 sbs-pf2 gunicorn[528714]: urllib.error.HTTPError: HTTP Error 404: NOT FOUND
```

Instead, the API should return a 400 with a descriptive error message (which includes the http error received when trying to fetch the logo).

**Comment by baszoetekouw** [comment]
tested
