### ISSUE TITLE
HTTP 500 on saving duplicatie organisation domain

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SBS#872]
```
Traceback (most recent call last):
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'eduid.nl' for key 'schac_home_organisation_name_unique'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/organisation.py", line 373, in update_organisation
    return update(Organisation, custom_json=data, allow_child_cascades=False,
  File "/opt/sbs/sbs/server/db/models.py", line 96, in update
    return _merge(cls, json_dict), 201
  File "/opt/sbs/sbs/server/db/models.py", line 45, in _merge
    db.session.commit()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 552, in commit
    return self._proxied.commit()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4299, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/sbs/sbs-env/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'eduid.nl' for key 'schac_home_organisation_name_unique'")
[SQL: INSERT INTO schac_home_organisations (name, organisation_id, created_by, updated_by) VALUES (%s, %s, %s, %s)]
[parameters: ('eduid.nl', 21, '[1b426f687a9f6bda71121cd66896f7e76ff46007@acc.sram.eduteams.org](mailto:1b426f687a9f6bda71121cd66896f7e76ff46007@acc.sram.eduteams.org)', '[1b426f687a9f6bda71121cd66896f7e76ff46007@acc.sram.eduteams.org](mailto:1b426f687a9f6bda71121cd66896f7e76ff46007@acc.sram.eduteams.org)')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by oharsta** [comment]
@FlorisFokkinga How were you able to submit the update? There is a check for duplicate schac_homes.

![Image](https://github.com/SURFscz/SBS/assets/530657/9b327cb5-187b-4374-8ed2-789d32c3b598)

**Comment by oharsta** [comment]
@FlorisFokkinga Able to reproduce - beat the validation by pressing submit directly

**Comment by FlorisFokkinga** [comment]
Fixed
