### ISSUE TITLE
Error 403 when creating a group with autoprovision via the Org API

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SBS#882]
When creating a new group in a CO with auto_provision_members=true, I get a 403:

```
curl -X POST "https://acc.sram.surf.nl/api/groups/v1" -H  "accept: application/json" -H  "Authorization: Bearer abcde" -H  "Content-Type: application/json" -d "{  \"name\": \"Ablabla2\",  \"description\": \"blabla2\",  \"short_name\": \"blabla2\",  \"auto_provision_members\": true,  \"collaboration_identifier\": \"9a450bd7-196e-4d8a-a9a1-9a94db9ed594\"}"
```
gives
```
{
  "error": true,
  "message": "Forbidden 403: https://acc.sram.surf.nl/api/groups/v1. IP: 2001:610:450:5a::5, 10.16.0.20"
}
```

Log show:
```
Aug 16 09:33:42 sbs-af1 gunicorn[78995]: ERROR [base] user: ext_api, <Response 117 bytes [403 FORBIDDEN]>
Aug 16 09:33:42 sbs-af1 gunicorn[78995]: Traceback (most recent call last):
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/api/base.py", line 170, in wrapper
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     body, status = f(*args, **kwargs)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs-env/lib/python3.9/site-packages/flasgger/utils.py", line 305, in wrapper
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     return function(*args, **kwargs)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/api/group.py", line 123, in create_group_api
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     res = create_group(collaboration.id, data)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/api/group.py", line 169, in create_group
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     auto_provision_all_members_and_invites(group)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/api/group.py", line 45, in auto_provision_all_members_and_invites
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     do_add_group_members({
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/api/group_members.py", line 19, in do_add_group_members
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     confirm_collaboration_admin(collaboration_id)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/auth/security.py", line 180, in confirm_collaboration_admin
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     confirm_write_access(override_func=override_func)
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/auth/security.py", line 108, in confirm_write_access
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     return confirm_scope_access(*args, override_func=override_func, scope="write")
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:   File "/opt/sbs/sbs/server/auth/security.py", line 99, in confirm_scope_access
Aug 16 09:33:42 sbs-af1 gunicorn[78995]:     raise Forbidden()
Aug 16 09:33:42 sbs-af1 gunicorn[78995]: werkzeug.exceptions.Forbidden: 403 Forbidden: Forbidden 403: https://acc.sram.surf.nl/api/groups/v1. IP: 2001:610:450:5a::5, 10.16.0.20
```

**Comment by baszoetekouw** [comment]
works
